import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { padding: 18, paddingTop: 2, paddingBottom: 40 },
    sectionTitle: { marginTop: 16, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary },
    rowBox: {
        paddingHorizontal: 18,
        paddingVertical: 12,
        borderRadius: 8,
        marginTop: 8,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
    },
    rowTitle: { height: 19, fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, lineHeight: 19 },
    rowText: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    rowStatus: { fontWeight: 400, fontSize: 14, color: '#00C950', marginTop: 4 },
    rowStatusWarn: { fontWeight: 400, fontSize: 14, color: '#EDC262', marginTop: 4 },
    rowStatusOrange: { fontWeight: 400, fontSize: 14, color: '#F97316', marginTop: 4 },
    rowStatusError: { fontWeight: 400, fontSize: 14, color: "#D80010", marginTop: 4 },
    rowLine: { height: 1, backgroundColor: '#E8DED2', width: "100%" },
    btmBox: { marginTop: 18 },
    startBtn: { paddingHorizontal: 20, height: 29, backgroundColor: '#053A93', borderRadius: 15 },
    startText: { fontWeight: 500, fontSize: 14, color: '#FFFFFF' },
    moreText: { marginTop: 16, fontWeight: 400, fontSize: 14, color: AppTheme.primaryColor },


    // add
    titleBox: { marginTop: 22 },
    leftTitle: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary },
    progressBarBox: { flex: 1, height: 10, backgroundColor: "rgba(5,58,147,0.24)", borderRadius: 5, marginHorizontal: 8 },
    progressBar: { height: 10, backgroundColor: AppTheme.primaryColor, borderRadius: 5 },
    questionBox: { marginTop: 28 },
    questionImg: { width: 40, height: 40 },
    questionBubbleWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', marginLeft: 7 },
    questionBubbleArrow: {
        width: 0,
        height: 0,
        borderTopWidth: 7,
        borderBottomWidth: 7,
        borderRightWidth: 8,
        borderTopColor: 'transparent',
        borderBottomColor: 'transparent',
        borderRightColor: '#FFFFFF',
        marginRight: -1,
        zIndex: 1,
    },
    questionBubble: {
        alignSelf: 'flex-start',
        flexShrink: 1,
        maxWidth: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingHorizontal: 14,
        paddingVertical: 12,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    questionText: { flexShrink: 1, fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, lineHeight: 22 },
    questionTitle: { marginTop: 28, marginLeft: 18, fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary, marginBottom: 4 },
    mapItem: { marginTop: 8, backgroundColor: "#FFFFFF", borderRadius: 8, padding: 18, borderWidth: 1, borderColor: "#FFFFFF" },
    mapItemActive: { borderColor: AppTheme.primaryColor, backgroundColor: "rgba(5,58,147,0.14)" },
    mapItemText: { fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary },
    fillBox: { marginTop: 8, backgroundColor: "#FFFFFF", borderRadius: 8, paddingHorizontal: 18, paddingVertical: 12 },
    fillLabel: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, marginBottom: 8 },
    fillInput: { fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, padding: 0 },
    bmiText: { marginTop: 12, textAlign: 'center', fontWeight: 500, fontSize: 16, color: AppTheme.primaryColor },
    bmiPlaceholder: { marginTop: 12, textAlign: 'center', fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    nextBtn: { marginTop: 12, marginHorizontal: 18, height: 45, backgroundColor: "#053A93", borderRadius: 8 },
    nextBtnDisabled: { opacity: 0.5 },
    nextBtnText: { height: 19, fontWeight: 500, fontSize: 16, color: "#FFFFFF" },



    // detail
    detailBox: {
        marginTop: 18,
        borderRadius: 8,
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: "#FFF",
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    detailTitle: { fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary },
    detailTime: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, marginTop: 6 },
    progressRing: { width: 60, height: 60, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    progressCanvas: { width: 60, height: 60, position: 'absolute' },
    progressText: { fontWeight: 500, fontSize: 12, color: '#FFBA1D', lineHeight: 14 },
    rowTextBox: { marginTop: 12 },
    topText: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary },
    detailMapTitle: { fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary, marginBottom: 4 },
    detailMapItem: { marginTop: 8, height: 34, backgroundColor: "#F7FAFF", borderRadius: 24, paddingLeft: 22 },
    detailMapItemText: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, },
    detailMapItemActive: { backgroundColor: "#E2EDFF", borderWidth: 1, borderColor: AppTheme.primaryColor },
    detailMapItemTextActive: { color: AppTheme.primaryColor },
    detailBottomText: { marginTop: 15, textAlign: 'center', fontWeight: 400, fontSize: 12, color: "rgba(153,153,153,0.67)" },



    //result
    resultCanvasBox: { width: 144, height: 144, justifyContent: "center", alignItems: "center", marginHorizontal: "auto" },
    resultTitle: { marginTop: 24, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, textAlign: "center", lineHeight: 52 },
    resultCanvas: { width: 144, height: 144, position: 'absolute' },
    resultScore: { textAlign: "center", fontWeight: 500, fontSize: 16, color: '#FFBA1D' },
    resultScoreBox: {
        marginTop: 23,
        width: 275,
        height: 159,
        backgroundColor: "#FFFFFF",
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        borderRadius: 8,
        margin: "auto",
        paddingHorizontal: 10,
        paddingVertical: 22
    },
    scoreBox: { flex: 1 },
    resultScoreTitle: { textAlign: "center", fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, lineHeight: 36 },
    resultScoreValue: { textAlign: "center", fontWeight: 400, fontSize: 16, color: AppTheme.textSecondary },
    rowLineBox: { marginTop: 12, paddingHorizontal: 12 },
    resultScoreTip: { marginTop: 16, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, margin: "auto" },
    reEvaluateBtn: { marginTop: 12, marginHorizontal: 18, marginBottom: 8, height: 45, backgroundColor: '#E2EDFF', borderRadius: 8 },
    reEvaluateBtnText: { height: 19, fontWeight: 500, fontSize: 16, color: '#053A93' },
})

export default styles;
