import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    pageContent: { flex: 1, position: 'relative' },
    body: { padding: 12, paddingTop: 2, paddingBottom: 14 },
    bodyStretch: { flexGrow: 1, paddingBottom: 0 },
    sectionTitle: { fontWeight: "bold", fontSize: 16, color: AppTheme.textPrimary },
    more: { fontWeight: 500, fontSize: 13, color: '#666666' },
    infoBox: {
        marginTop: 10,
        padding: 15,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FEFFFF",
        borderRadius: 8,
    },
    rowBox: {
        padding: 15,
        borderRadius: 8,
        marginTop: 12,
        backgroundColor: '#F6F8FB',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
    },
    timeIcon: { width: 16, height: 16 },
    rowTitle: { fontWeight: "bold", fontSize: 16, color: AppTheme.textPrimary },
    rowText: { fontWeight: 400, fontSize: 14, marginTop: 6, color: AppTheme.textSecondary },
    rowTitleText: { fontWeight: "bold", fontSize: 18, color: AppTheme.textPrimary },
    rowStatus: {
        height: 22,
        paddingHorizontal: 6,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#6D925E',
        overflow: 'hidden',
        fontWeight: 'bold',
        fontSize: 12,
        color: '#6D925E',
        lineHeight: 20,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    rowStatusWarn: {
        height: 22,
        paddingHorizontal: 6,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#EDC262',
        overflow: 'hidden',
        fontWeight: 'bold',
        fontSize: 12,
        color: '#EDC262',
        lineHeight: 20,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    rowStatusOrange: {
        height: 22,
        paddingHorizontal: 6,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#F97316',
        overflow: 'hidden',
        fontWeight: 'bold',
        fontSize: 12,
        color: '#F97316',
        lineHeight: 20,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    rowStatusError: {
        height: 22,
        paddingHorizontal: 6,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#D80010',
        overflow: 'hidden',
        fontWeight: 'bold',
        fontSize: 12,
        color: '#D80010',
        lineHeight: 20,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    rowLine: { height: 1, backgroundColor: '#E8DED2', width: "100%" },
    btmBox: { marginTop: 12 },
    iconSize: {
        width: 47,
        height: 47
    },
    startBtn: { paddingHorizontal: 20, height: 29, backgroundColor: '#FFFFFF', borderRadius: 15 },
    startBtnDisabled: { backgroundColor: '#EEF0F3' },
    startText: { fontWeight: 500, fontSize: 14, color: '#6D925E' },
    startTextDisabled: { color: '#999999' },
    moreText: { marginTop: 16, fontWeight: 400, fontSize: 14, color: AppTheme.primaryColor },


    // add
    titleBox: { marginTop: 22 },
    leftTitle: { fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary },
    leftTitleNumber: { fontWeight: 500, fontSize: 18, color: AppTheme.primaryColor },
    progressBarBox: { flex: 1, height: 10, backgroundColor: "#FFFFFF", borderRadius: 5, marginHorizontal: 8 },
    progressBar: { height: 10, backgroundColor: AppTheme.primaryColor, borderRadius: 5 },
    questionBox: {
        marginTop: 28,
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        borderWidth: 1,
        borderColor: '#FFFFFF',
        overflow: 'hidden',
    },
    questionBoxStretch: {
        flex: 1,
        marginBottom: 0,
        borderBottomWidth: 0,
    },
    questionBoxGradient: {
        paddingHorizontal: 12,
        paddingTop: 20,
        paddingBottom: 24,
    },
    questionBoxGradientStretch: {
        flex: 1,
        flexGrow: 1,
        paddingBottom: 16,
    },
    heightWeightBox: {
        flex: 1,
    },
    heightWeightContent: {
        flex: 1,
    },
    bmiFooter: {
        marginTop: 'auto',
        paddingTop: 24,
        paddingBottom: 8,
    },
    questionHeader: { marginBottom: 4 },
    questionBubbleLeftTitle: {
        fontWeight: 500,
        fontSize: 14,
        color: AppTheme.textPrimary,
    },
    questionBubbleLeftText: {
        fontWeight: 500,
        fontSize: 12,
        color: AppTheme.textSecondary
    },
    questionBubble: {
        marginTop: 32,
        marginBottom: 10
    },
    questionBubbleIcon: {
        marginTop: 8,
        width: 4,
        height: 11,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 25,
    },
    questionText: { flexShrink: 1, fontWeight: "bold", fontSize: 16, color: AppTheme.textPrimary, marginLeft: 6, lineHeight: 26 },
    lineBox: { height: 1, backgroundColor: '#EFF4F5', marginTop: 12 },
    mapItem: {
        marginTop: 8,
        height: 57,
        backgroundColor: '#F6F7FA',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    mapItemActive: {
        backgroundColor: 'rgba(109,146,94,0.12)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    mapItemText: {
        fontWeight: '500',
        fontSize: 15,
        color: '#333333',
        textAlign: 'center',
    },
    mapItemTextActive: {
        fontWeight: 'bold',
        fontSize: 15,
        color: '#6D925E',
    },
    fillBox: { marginTop: 8, backgroundColor: "#FFFFFF", borderRadius: 8, paddingHorizontal: 18, paddingVertical: 12 },
    fillLabel: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, marginBottom: 8 },
    fillInput: { fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, padding: 0 },
    bmiText: { textAlign: 'center', fontWeight: 500, fontSize: 16, color: AppTheme.primaryColor },
    bmiPlaceholder: { textAlign: 'center', fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    bottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 18,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    bottomBarButtonLeft: {
        height: 50,
        backgroundColor: '#6D925E',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#6D925E',
    },
    bottomBarButtonTextLeft: {
        fontWeight: 'bold',
        fontSize: 18,
        color: '#FFFFFF',
    },
    nextBtn: { marginTop: 12, marginHorizontal: 18, height: 45, backgroundColor: "#053A93", borderRadius: 8 },
    nextBtnDisabled: { opacity: 0.5 },
    nextBtnText: { height: 19, fontWeight: 500, fontSize: 16, color: "#FFFFFF" },



    // detail
    detailBox: {
        marginTop: 18,
        borderRadius: 8,
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: "#FFF",
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    detailTitle: { fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary },
    detailTime: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, marginTop: 6 },
    progressRing: { width: 60, height: 60, justifyContent: 'center', alignItems: 'center' },
    progressCanvas: { width: 60, height: 60, position: 'absolute' },
    progressText: { fontWeight: 500, fontSize: 12, color: '#FFBA1D', lineHeight: 14 },
    rowTextBox: { marginTop: 12 },
    topText: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary },
    detailMapTitle: { fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary, marginBottom: 4 },
    detailMapItem: { marginTop: 8, height: 34, backgroundColor: "#F7FAFF", borderRadius: 24, paddingLeft: 22 },
    detailMapItemText: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    detailMapItemActive: { backgroundColor: "#E2EDFF", borderWidth: 1, borderColor: AppTheme.primaryColor },
    detailMapItemTextActive: { color: AppTheme.primaryColor },
    detailBottomText: { marginTop: 15, textAlign: 'center', fontWeight: 400, fontSize: 12, color: "rgba(153,153,153,0.67)" },



    //result
    resultCanvasBox: { width: 182, height: 182, justifyContent: "center", alignItems: "center", marginHorizontal: "auto" },
    resultTitle: { marginTop: 24, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, textAlign: "center", lineHeight: 52 },
    resultCanvas: { width: 182, height: 182, position: 'absolute' },
    resultScore: { textAlign: "center", fontWeight: 500, fontSize: 16, color: '#FFBA1D' },
    resultScoreBox: {
        marginTop: 23,
        width: 275,
        height: 159,
        backgroundColor: "#FFFFFF",
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        borderRadius: 8,
        margin: "auto",
        paddingHorizontal: 10,
        paddingVertical: 22
    },
    scoreBox: { flex: 1 },
    resultScoreTitle: { textAlign: "center", fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, lineHeight: 36 },
    resultScoreValue: { textAlign: "center", fontWeight: 400, fontSize: 16, color: AppTheme.textSecondary },
    rowLineBox: { marginTop: 12, paddingHorizontal: 12 },
    resultScoreTip: { marginTop: 16, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, margin: "auto" },
    reEvaluateBtn: { marginTop: 12, marginHorizontal: 18, marginBottom: 8, height: 45, backgroundColor: '#E2EDFF', borderRadius: 8 },
    reEvaluateBtnText: { height: 19, fontWeight: 500, fontSize: 16, color: '#053A93' },
})

export default styles;
