import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  headerGradient: { position: 'absolute', top: 0, left: 0, right: 0, height: 310 },
  headerWrap: { paddingLeft: 10, overflow: 'hidden' },
  pageLine: { height: 1, marginTop: 10, backgroundColor: 'rgba(5,58,147,0.06)' },
  scroll: { paddingHorizontal: 18, paddingBottom: 40 },
  timeText: { fontWeight: 400, fontSize: 16, textAlign: "center", marginTop: 12, color: AppTheme.textPrimary },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  aiMessageBox: { marginTop: 13 },
  aiMessageBubbleWrap: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', marginLeft: 7 },
  aiMessageBubbleArrow: {
    width: 0,
    height: 0,
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderRightWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderRightColor: '#FFFFFF',
    marginTop: 16,
    marginRight: -1,
    zIndex: 1,
  },
  aiMessageBoxContent: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  aiMessageText: { fontWeight: '400', fontSize: 16, color: AppTheme.textPrimary, lineHeight: 24, flexShrink: 1 },
  aiMessageTextBold: { fontWeight: '600', fontSize: 16, color: AppTheme.textPrimary, lineHeight: 24 },
  aiMessageTextItalic: {
    fontSize: 16,
    color: AppTheme.primaryColor,
    lineHeight: 24,
    fontWeight: '500',
  },
  aiMessageTextBoldItalic: {
    fontSize: 16,
    color: AppTheme.primaryColor,
    lineHeight: 24,
    fontWeight: '600',
  },
  myMessageBox: { marginTop: 12 },
  myMessageBubbleWrap: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'flex-end', marginRight: 7 },
  myMessageBubbleArrow: {
    width: 0,
    height: 0,
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#FFFFFF',
    marginTop: 16,
    marginLeft: -1,
    zIndex: 1,
  },
  myMessageBoxContent: {
    alignSelf: 'flex-end',
    maxWidth: '92%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  chatBody: { flex: 1 },
  loadingBox: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  quickActionRow: {
    marginBottom: 7,
    paddingTop: 10,
    paddingBottom: 4,
    backgroundColor: AppTheme.backgroundColor,
    flexGrow: 0,
  },
  quickActionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 18,
  },
  quickActionBtn: {
    height: 30,
    paddingHorizontal: 24,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  quickActionText: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    color: '#333333',
  },
  inputSection: {
    backgroundColor: AppTheme.backgroundColor,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 12,
  },
  inputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
    maxHeight: 120,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    paddingLeft: 14,
    paddingRight: 4,
    overflow: 'visible',
  },
  input: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    paddingVertical: 10,
    fontSize: 16,
    color: AppTheme.textPrimary,
  },
  sendBtn: {
    marginLeft: 10,
    minWidth: 64,
    height: 40,
    borderRadius: 12,
    backgroundColor: AppTheme.primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  sendBtnDisabled: {
    opacity: 0.5,
  },
  sendBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  addBtn: {
    marginLeft: 10,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addIcon: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  typingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 24,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  typingDotInactive: {
    backgroundColor: '#999999',
  },
  typingDotActive: {
    backgroundColor: '#053A93',
  },
  uploadPanel: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 21,
    paddingBottom: 8,
    backgroundColor: AppTheme.backgroundColor,
  },
  bottomArea: {
    overflow: 'hidden',
    backgroundColor: AppTheme.backgroundColor,
  },
  uploadPanelItem: {
    alignItems: 'center',
    minWidth: 80,
  },
  uploadPanelImg: {
    width: 68,
    height: 68,
  },
  uploadPanelTitle: {
    marginTop: 11,
    fontWeight: '400',
    fontSize: 15,
    color: AppTheme.textPrimary,
    lineHeight: 18,
  },
});

export default styles;
