import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  headerGradient: { position: 'absolute', top: 0, left: 0, right: 0, height: 310 },
  headerWrap: { paddingLeft: 10, overflow: 'hidden' },
  pageLine: { height: 1, marginTop: 10, backgroundColor: 'rgba(5,58,147,0.06)' },
  scroll: { paddingHorizontal: 18, paddingBottom: 40 },
  navIcon: { width: 24, height: 24 },
  timeText: { fontWeight: 400, fontSize: 16, textAlign: "center", marginTop: 12, color: AppTheme.textPrimary },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  avatarSpacer: { width: 40, height: 40 },
  aiMedicationCardWrap: { flex: 1, marginLeft: 7 },
  medicationReminderBox: {
    alignSelf: 'flex-start',
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2
  },
  medicationReminderRow: { width: '100%' },
  medicationReminderRowGap: { marginTop: 14 },
  medicationReminderLeftCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'flex-start',
  },
  medicationReminderCenterCol: {
    flexShrink: 0,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  medicationReminderRightCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'flex-end',
  },
  medicationReminderName: {
    flexShrink: 1,
    fontWeight: '500',
    fontSize: 14,
    color: AppTheme.textPrimary,
  },
  medicationReminderDose: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 14,
    color: AppTheme.textSecondary,
  },
  medicationReminderTime: {
    marginRight: 8,
    fontWeight: '400',
    fontSize: 14,
    color: AppTheme.textSecondary,
  },
  medicationReminderStatusTaken: {
    fontSize: 12,
    color: '#34B69F',
  },
  medicationReminderStatusPending: {
    fontSize: 12,
    color: '#FF8B07',
  },
  medicationBadgeCF: {
    marginLeft: 6,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(5,58,147,0.14)',
    justifyContent: 'center',
  },
  medicationBadgeCFText: { fontSize: 11, color: '#053A93' },
  medicationBadgeGR: {
    marginLeft: 6,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(52,182,159,0.12)',
    justifyContent: 'center',
  },
  medicationBadgeGRText: { fontSize: 11, color: '#34B69F' },
  medicationAdviceBox: {
    marginTop: 10,
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  medicationAdviceTitle: {
    fontWeight: '500',
    fontSize: 14,
    color: AppTheme.textPrimary,
  },
  medicationAdviceText: {
    marginTop: 6,
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 20,
    color: AppTheme.textSecondary,
  },
  questionnaireReminderBox: {
    alignSelf: 'flex-start',
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  questionnaireReminderRow: { marginTop: 14 },
  questionnaireReminderIcon: { width: 34, height: 34, borderRadius: 18 },
  questionnaireReminderTitleCol: {
    flex: 1,
    minWidth: 0,
    marginLeft: 8,
  },
  questionnaireReminderTitle: {
    fontWeight: '400',
    fontSize: 14,
    color: AppTheme.textPrimary,
  },
  questionnaireNextAssessmentText: {
    marginTop: 6,
    fontSize: 11,
    color: AppTheme.textSecondary,
  },
  questionnaireReminderDuration: {
    width: 72,
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 12,
    color: AppTheme.textSecondary,
  },
  questionnaireStartBtn: {
    minWidth: 68,
    height: 28,
    borderRadius: 14,
    backgroundColor: AppTheme.primaryColor,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  questionnaireStartBtnDisabled: {
    backgroundColor: '#E8E8E8',
  },
  questionnaireStartBtnText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  questionnaireStartBtnTextDisabled: {
    color: '#999999',
  },
  aiMessageBox: { marginTop: 13 },
  aiMessageBoxFollowUp: { marginTop: 19 },
  aiMessageBubbleWrap: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', marginLeft: 7 },
  aiMessageBubbleArrow: {
    width: 0,
    height: 0,
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderRightWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderRightColor: '#FFFFFF',
    marginTop: 16,
    marginRight: -1,
    zIndex: 1,
  },
  aiMessageBoxContent: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  aiMessageText: { fontWeight: '400', fontSize: 16, color: AppTheme.textPrimary, lineHeight: 24, flexShrink: 1 },
  aiMessageTextBold: { fontWeight: '600', fontSize: 16, color: AppTheme.textPrimary, lineHeight: 24 },
  aiMessageTextItalic: {
    fontSize: 16,
    color: AppTheme.primaryColor,
    lineHeight: 24,
    fontWeight: '500',
  },
  aiMessageTextBoldItalic: {
    fontSize: 16,
    color: AppTheme.primaryColor,
    lineHeight: 24,
    fontWeight: '600',
  },
  myMessageBox: { marginTop: 12 },
  myMessageBubbleWrap: { flex: 1, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'flex-end', marginRight: 7 },
  myMessageBubbleArrow: {
    width: 0,
    height: 0,
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderLeftWidth: 8,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#FFFFFF',
    marginTop: 16,
    marginLeft: -1,
    zIndex: 1,
  },
  myMessageBoxContent: {
    alignSelf: 'flex-end',
    maxWidth: '92%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  myMessageImageContent: {
    paddingHorizontal: 4,
    paddingVertical: 4,
  },
  myMessageImageWrap: {
    width: 120,
    height: 120,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#DFE6F1',
    alignSelf: 'flex-end',
  },
  myMessageImage: {
    width: '100%',
    height: '100%',
  },
  myMessageImageFallback: {
    flex: 1,
  },
  myMessageImageCountBadge: {
    position: 'absolute',
    right: 4,
    bottom: 4,
    backgroundColor: 'rgba(5,58,147,0.72)',
    borderRadius: 8,
    paddingHorizontal: 8,
    minWidth: 22,
    alignItems: 'center',
  },
  myMessageImageCountText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  myMessageDocumentCard: {
    minWidth: 220,
    maxWidth: 280,
    paddingVertical: 10,
  },
  myMessageDocumentIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: AppTheme.backgroundColor,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  myMessageDocumentMeta: {
    flex: 1,
    minWidth: 0,
  },
  myMessageDocumentName: {
    color: AppTheme.textPrimary,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    flexShrink: 1,
  },
  myMessageDocumentSize: {
    color: AppTheme.textSecondary,
    fontSize: 12,
    marginTop: 4,
  },
  myMessageTextWithAttachment: {
    marginTop: 8,
  },
  uploadPreviewModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
  },
  uploadPreviewModalCloseArea: {
    ...StyleSheet.absoluteFillObject,
  },
  uploadPreviewModalContent: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 48,
  },
  uploadPreviewModalPage: {
    width: 320,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  uploadPreviewModalImage: {
    width: 288,
    height: 360,
    borderRadius: 10,
  },
  uploadPreviewModalName: {
    color: '#A1A1AA',
    fontSize: 12,
    marginTop: 12,
    textAlign: 'center',
    maxWidth: 288,
  },
  uploadPreviewModalCloseBtn: {
    alignSelf: 'center',
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  uploadPreviewModalCloseText: {
    color: '#FFFFFF',
    fontSize: 16,
  },
  chatBody: { flex: 1 },
  loadingBox: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  quickActionRow: {
    flexGrow: 0,
    flexShrink: 0,
    backgroundColor: 'transparent',
  },
  quickActionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 8,
  },
  quickActionBtn: {
    height: 30,
    paddingHorizontal: 24,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  quickActionText: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    color: '#333333',
  },
  inputSection: {
    backgroundColor: AppTheme.backgroundColor,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 0,
    paddingBottom: 12,
  },
  inputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
    maxHeight: 120,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    paddingLeft: 14,
    paddingRight: 4,
    overflow: 'visible',
  },
  input: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    paddingVertical: 10,
    fontSize: 16,
    color: AppTheme.textPrimary,
  },
  sendBtn: {
    marginLeft: 10,
    minWidth: 64,
    height: 40,
    borderRadius: 12,
    backgroundColor: AppTheme.primaryColor,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  sendBtnDisabled: {
    opacity: 0.5,
  },
  sendBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  addBtn: {
    marginLeft: 10,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addIcon: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  typingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 24,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  typingDotInactive: {
    backgroundColor: '#999999',
  },
  typingDotActive: {
    backgroundColor: '#053A93',
  },
  uploadPanel: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 21,
    paddingBottom: 8,
    backgroundColor: AppTheme.backgroundColor,
  },
  bottomArea: {
    overflow: 'hidden',
    backgroundColor: AppTheme.backgroundColor,
  },
  uploadPanelItem: {
    alignItems: 'center',
    minWidth: 80,
  },
  uploadPanelImg: {
    width: 68,
    height: 68,
  },
  uploadPanelTitle: {
    marginTop: 11,
    fontWeight: '400',
    fontSize: 15,
    color: AppTheme.textPrimary,
    lineHeight: 18,
  },
});

export default styles;
