import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  scroll: { padding: 12, paddingTop: 8, paddingBottom: 40, flex: 1 },
  topBox: { marginTop: 10, paddingHorizontal: 22 },
  topBoxImage: { width: 15, height: 15, marginRight: 3 },
  topBoxText: { fontSize: 13, fontWeight: 500, color: AppTheme.primaryColor },
  topNameBox: { marginTop: 27, position: 'relative', minHeight: 70 },
  topNameText: { fontWeight: 'bold', fontSize: 22, color: '#000000' },
  containerBox: {
    marginLeft: 8,
    height: 22,
    paddingHorizontal: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  topNameImage: { width: 12, height: 12, marginRight: 3 },
  cfText: { fontWeight: 'bold', fontSize: 12, color: '#6D925E' },
  rightImg: { width: 70, height: 70, position: 'absolute', right: 0, top: 0 },
  topInfoBox: { marginTop: 12 },
  topInfoText: { fontWeight: 500, fontSize: 12, color: '#666666' },
  brBox: {
    height: 17,
    paddingHorizontal: 4,
    backgroundColor: '#6D925E',
    borderRadius: 4,
    marginRight: 6,
  },
  brText: { fontWeight: 'bold', fontSize: 12, color: '#FFFFFF' },
  navBox: {
    marginHorizontal: 12,
    marginTop: 20,
    height: 40,
    padding: 3,
    backgroundColor: 'rgba(109,146,94,0.12)',
    borderRadius: 25,
    gap: 6,
  },
  navItem: { flex: 1, height: '100%', borderRadius: 25, paddingHorizontal: 12 },
  activeNavItem: { backgroundColor: '#FFF' },
  navIcon: { width: 18, height: 18, marginRight: 3 },
  navText: { fontWeight: 500, fontSize: 14, color: AppTheme.textPrimary },
  activeNavText: { fontWeight: 'bold' },
  emptyPrescription: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyPrescriptionIcon: {
    marginTop: -60,
    width: 80,
    height: 80,
  },
  emptyPrescriptionText: {
    marginTop: 25,
    fontWeight: '500',
    fontSize: 14,
    color: '#999999',
    textAlign: 'center',
  },
  emptyPrescriptionTextRow: {
    marginTop: 25,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyPrescriptionTextInline: {
    fontWeight: '500',
    fontSize: 14,
    color: '#999999',
  },
  calendarBox: { marginTop: 18, height: 64, paddingHorizontal: 13 },
  calendarCol: { width: 38, height: '100%', borderRadius: 25, backgroundColor: 'transparent' },
  calendarColActive: { backgroundColor: 'rgba(109,146,94,0.12)' },
  calendarTitle: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#666666',
    marginTop: 12,
    textAlign: 'center',
  },
  calendarTitleActive: {
    fontWeight: 'bold',
    fontSize: 13,
    color: AppTheme.primaryColor,
    marginTop: 12,
    textAlign: 'center',
  },
  calendarSubtitle: {
    fontWeight: 500,
    fontSize: 18,
    marginTop: 5,
    color: AppTheme.textPrimary,
    textAlign: 'center',
  },
  calendarSubtitleActive: {
    fontWeight: 500,
    fontSize: 18,
    marginTop: 5,
    color: AppTheme.primaryColor,
    textAlign: 'center',
  },
  calendarImage: { width: 22, height: 22, marginTop: 5, margin: 'auto' },
  trainingStatRow: {
    marginTop: 12,
    flexDirection: 'row',
    gap: 9,
  },
  trainingStatCard: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 2,
  },
  trainingStatIcon: {
    width: 18,
    height: 18,
  },
  trainingStatValue: {
    marginTop: 8,
    fontWeight: 'bold',
    fontSize: 18,
    color: '#333333',
  },
  trainingStatLabel: {
    marginTop: 4,
    fontWeight: '500',
    fontSize: 12,
    color: '#999999',
  },
  trainingProgressTrack: {
    marginTop: 12,
    height: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    overflow: 'hidden',
  },
  trainingProgressFill: {
    height: 8,
    backgroundColor: '#6D925E',
    borderRadius: 25,
  },
  trainingPhaseTabBox: {
    marginTop: 12,
    height: 40,
    padding: 3,
    backgroundColor: '#EDEEEF',
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
  },
  trainingPhaseTabItem: {
    flex: 1,
    height: 34,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trainingPhaseTabItemActive: {
    backgroundColor: '#FFFFFF',
  },
  trainingPhaseTabIcon: {
    width: 18,
    height: 18,
  },
  trainingPhaseTabText: {
    marginLeft: 4,
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  trainingPhaseContent: {
    marginTop: 12,
    width: '100%',
    alignSelf: 'stretch',
    overflow: 'hidden',
  },
  trainingPhaseBanner: {
    borderRadius: 12,
  },
  trainingPhaseBannerWrap: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
  },
  trainingPhaseBannerBox: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '65%',
    padding: 20,
    justifyContent: 'center',
  },
  trainingPhaseBannerTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  trainingPhaseBannerValue: {
    marginTop: 6,
    fontWeight: '500',
    fontSize: 13,
    color: '#666666',
    lineHeight: 20,
  },
  trainingExerciseCard: {
    marginTop: 12,
    height: 80,
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  trainingExerciseThumb: {
    width: 50,
    height: 50,
    borderRadius: 6,
  },
  trainingExerciseInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
  },
  trainingExerciseTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  trainingExerciseDuration: {
    marginTop: 4,
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
  },
  trainingExerciseCheck: {
    width: 20,
    height: 20,
    flexShrink: 0,
  },
  trainingPhaseContentTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  mainTrainingModule: {
    marginTop: 12,
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
    position: 'relative',
    overflow: 'visible',
  },
  mainTrainingCheckIn: {
    position: 'absolute',
    right: 0,
    bottom: 16,
    backgroundColor: '#FFEAC0',
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    padding: 8,
    gap: 4,
  },
  mainTrainingCheckInIcon: {
    width: 18,
    height: 18,
  },
  mainTrainingCheckInText: {
    fontWeight: 'bold',
    fontSize: 12,
    color: '#CD471C',
  },
  mainTrainingModuleIcon: {
    width: 18,
    height: 18,
  },
  mainTrainingModuleTitleWrap: {
    marginLeft: 4,
    position: 'relative',
    alignSelf: 'flex-start',
  },
  mainTrainingModuleUnderline: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 7,
    borderRadius: 25,
  },
  mainTrainingModuleTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  mainTrainingModuleTipText: {
    marginLeft: 6,
    fontWeight: 500,
    fontSize: 12,
    color: "#999999",
  },
  mainTrainingActionRow: {
    marginTop: 20,
  },
  mainTrainingActionDivider: {
    marginTop: 20,
    height: 1,
    backgroundColor: 'rgba(23,63,125,0.08)',
  },
  mainTrainingActionThumb: {
    width: 50,
    height: 50,
    borderRadius: 6,
    flexShrink: 0,
  },
  mainTrainingActionInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  mainTrainingActionTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  mainTrainingActionDesc: {
    marginTop: 6,
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
  },
  mainTrainingActionTimer: {
    flexShrink: 0,
    marginLeft: 8,
    paddingHorizontal: 17,
    paddingVertical: 9,
    backgroundColor: 'rgba(109,146,94,0.2)',
    borderRadius: 25,
    gap: 4,
  },
  mainTrainingActionTimerIcon: {
    width: 15,
    height: 15,
  },
  mainTrainingActionTimerText: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#6D925E',
  },
  mainTrainingSetProgress: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  mainTrainingSetProgressTotal: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#999999',
  },
  mainTrainingSetRow: {
    marginTop: 12,
  },
  mainTrainingSetDoneIcon: {
    width: 27,
    height: 27,
    marginRight: 8,
  },
  mainTrainingSetTag: {
    height: 27,
    marginRight: 8,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  mainTrainingSetTagLast: {
    marginRight: 0,
  },
  mainTrainingSetTagText: {
    fontWeight: '500',
    fontSize: 12,
    color: '#333333',
  },
  mainTrainingSetDurationIcon: {
    width: 11,
    height: 11,
    marginRight: 4,
  },
  mainTrainingTipBox: {
    marginTop: 12,
    padding: 12,
    backgroundColor: 'rgba(254,248,225,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(238,156,68,0.3)',
  },
  mainTrainingTipIcon: {
    width: 15,
    height: 15,
  },
  mainTrainingTipTitle: {
    marginLeft: 6,
    fontWeight: 'bold',
    fontSize: 14,
    color: '#C98A41',
  },
  mainTrainingTipText: {
    marginTop: 8,
    fontWeight: '500',
    fontSize: 13,
    color: '#C98A41',
    lineHeight: 20,
  },
  mainTrainingModuleTagRow: {
    flexShrink: 0,
    marginLeft: 8,
    gap: 6,
  },
  mainTrainingModuleTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#F7F7F8',
    borderRadius: 25,
  },
  mainTrainingModuleTagText: {
    fontWeight: '500',
    fontSize: 11,
    color: '#000000',
  },
  mainTrainingHrRow: {
    marginVertical: 20,
  },
  mainTrainingHrIcon: {
    width: 50,
    height: 50,
    flexShrink: 0,
  },
  mainTrainingHrInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  mainTrainingHrLabel: {
    flex: 1,
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
  },
  mainTrainingHrBadge: {
    marginLeft: 8,
    paddingHorizontal: 6,
    paddingVertical: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  mainTrainingHrBadgeText: {
    fontWeight: 'bold',
    fontSize: 11,
    color: '#6D925E',
  },
  mainTrainingHrValue: {
    marginTop: 2,
    fontWeight: 'bold',
    fontSize: 22,
    color: '#333333',
  },
  mainTrainingHrUnit: {
    fontWeight: '500',
    fontSize: 12,
    color: '#999999',
  },
  mainTrainingDivider: {
    height: 1,
    backgroundColor: 'rgba(23,63,125,0.08)',
  },
  mainTrainingPlayerRow: {
    paddingTop: 30,
    paddingBottom: 15,
    gap: 22,
  },
  mainTrainingPlayerSideIcon: {
    width: 50,
    height: 50,
  },
  mainTrainingPlayerCenter: {
    width: 125,
    height: 125,
    backgroundColor: '#F7F8FF',
    borderRadius: 80,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  mainTrainingPlayerCenterText: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mainTrainingPlayerTime: {
    fontStyle: 'normal',
    fontWeight: 'bold',
    fontSize: 20,
    color: '#333333',
    letterSpacing: -0.8,
    transform: [{ scaleX: 0.95 }],
  },
  mainTrainingPlayerGoal: {
    marginTop: 8,
    fontWeight: '500',
    fontSize: 12,
    color: '#666666',
  },
  calendarContent: {
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginTop: 12,
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  bottomBar: {
    width: '100%',
    paddingHorizontal: 15,
    paddingTop: 17,
    backgroundColor: '#FEFEFE',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    shadowColor: '#B4C9FF',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 4,
    elevation: 3,
  },
  bottomBarButtonLeft: {
    flex: 2,
    height: 46,
    marginRight: 12,
    backgroundColor: '#6D925E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  bottomBarButtonIcon: {
    width: 20,
    height: 20,
    marginRight: 4,
  },
  bottomBarButtonTextLeft: { fontWeight: 'bold', fontSize: 16, color: '#FFFFFF' },
});

export default styles;
