import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  scroll: { padding: 12, paddingTop: 8, paddingBottom: 40, flex: 1 },
  topBox: { marginTop: 10, paddingHorizontal: 22 },
  topBoxImage: { width: 15, height: 15, marginRight: 3 },
  topBoxText: { fontSize: 13, fontWeight: 500, color: AppTheme.primaryColor },
  topNameBox: { marginTop: 27, position: 'relative', minHeight: 70 },
  topNameText: { fontWeight: 'bold', fontSize: 22, color: '#000000' },
  containerBox: {
    marginLeft: 8,
    height: 22,
    paddingHorizontal: 6,
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  topNameImage: { width: 12, height: 12, marginRight: 3 },
  cfText: { fontWeight: 'bold', fontSize: 12, color: '#6D925E' },
  rightImg: { width: 70, height: 70, position: 'absolute', right: 0, top: 0 },
  topInfoBox: { marginTop: 12 },
  topInfoText: { fontWeight: 500, fontSize: 12, color: '#666666' },
  brBox: {
    height: 17,
    paddingHorizontal: 4,
    backgroundColor: '#6D925E',
    borderRadius: 4,
    marginRight: 6,
  },
  brText: { fontWeight: 'bold', fontSize: 12, color: '#FFFFFF' },
  navBox: {
    marginHorizontal: 12,
    marginTop: 20,
    height: 40,
    padding: 3,
    backgroundColor: 'rgba(109,146,94,0.12)',
    borderRadius: 25,
    gap: 6,
  },
  navItem: { flex: 1, height: '100%', borderRadius: 25, paddingHorizontal: 12 },
  activeNavItem: { backgroundColor: '#FFF' },
  navIcon: { width: 18, height: 18, marginRight: 3 },
  navText: { fontWeight: 500, fontSize: 14, color: AppTheme.textPrimary },
  activeNavText: { fontWeight: 'bold' },
  emptyPrescription: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyPrescriptionIcon: {
    marginTop: -60,
    width: 80,
    height: 80,
  },
  emptyPrescriptionText: {
    marginTop: 25,
    fontWeight: '500',
    fontSize: 14,
    color: '#999999',
    textAlign: 'center',
  },
  emptyPrescriptionTextRow: {
    marginTop: 25,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyPrescriptionTextInline: {
    fontWeight: '500',
    fontSize: 14,
    color: '#999999',
  },
  calendarBox: { marginTop: 18, height: 64, paddingHorizontal: 13 },
  calendarCol: { width: 38, height: '100%', borderRadius: 25, backgroundColor: 'transparent' },
  calendarColActive: { backgroundColor: 'rgba(109,146,94,0.12)' },
  calendarTitle: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#666666',
    marginTop: 12,
    textAlign: 'center',
  },
  calendarTitleActive: {
    fontWeight: 'bold',
    fontSize: 13,
    color: AppTheme.primaryColor,
    marginTop: 12,
    textAlign: 'center',
  },
  calendarSubtitle: {
    fontWeight: 500,
    fontSize: 18,
    marginTop: 5,
    color: AppTheme.textPrimary,
    textAlign: 'center',
  },
  calendarSubtitleActive: {
    fontWeight: 500,
    fontSize: 18,
    marginTop: 5,
    color: AppTheme.primaryColor,
    textAlign: 'center',
  },
  calendarImage: { width: 22, height: 22, marginTop: 5, margin: 'auto' },
  calendarContent: {
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginTop: 12,
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  bottomBar: {
    width: '100%',
    paddingHorizontal: 15,
    paddingTop: 17,
    backgroundColor: '#FEFEFE',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    shadowColor: '#B4C9FF',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 4,
    elevation: 3,
  },
  bottomBarButtonLeft: {
    flex: 2,
    height: 46,
    marginRight: 12,
    backgroundColor: '#6D925E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  bottomBarButtonTextLeft: { fontWeight: 'bold', fontSize: 16, color: '#FFFFFF' },
});

export default styles;
