import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  scroll: { paddingTop: 8, paddingBottom: 40, flex: 1 },
  prescriptionMetaCard: {
    marginHorizontal: 12,
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  prescriptionMetaIcon: {
    width: 12,
    height: 12,
    marginRight: 6,
  },
  prescriptionMetaText: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#333333',
  },
  prescriptionMetaTextGreen: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#6D925E',
  },
  prescriptionSectionOuter: {
    marginHorizontal: 12,
    marginTop: 12,
    position: 'relative',
    overflow: 'visible',
  },
  prescriptionSectionWrap: {
    marginTop: 11,
    position: 'relative',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  prescriptionSectionCard: {
    height: 42,
    paddingHorizontal: 12,
    position: 'relative',
  },
  prescriptionSectionHeader: {
    height: 42,
    paddingRight: 60,
    flexDirection: 'row',
    alignItems: 'center',
  },
  prescriptionSectionHeaderIcon: {
    width: 18,
    height: 18,
    marginRight: 6,
  },
  prescriptionSectionHeaderTitle: {
    fontWeight: 'bold',
    fontSize: 13,
    lineHeight: 18,
    color: '#333333',
    includeFontPadding: false,
  },
  prescriptionSectionAiIcon: {
    position: 'absolute',
    right: 15,
    top: 0,
    width: 53,
    height: 53,
    zIndex: 2,
  },
  prescriptionSectionBody: {
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
    overflow: 'visible',
  },
  prescriptionSectionBodyTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#333333',
  },
  prescriptionSectionBodyDesc: {
    marginTop: 8,
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
    lineHeight: 23,
  },
  prescriptionSectionStats: {
    marginTop: 20,
    overflow: 'visible',
  },
  prescriptionSectionStatItem: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  prescriptionSectionStatBadge: {
    position: 'absolute',
    top: -16,
    right: -30,
    height: 16,
    paddingHorizontal: 5,
    backgroundColor: '#EE9C44',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  prescriptionSectionStatBadgeText: {
    fontWeight: '500',
    fontSize: 10,
    color: '#FFFFFF',
    lineHeight: 16,
    includeFontPadding: false,
  },
  prescriptionSectionStatTitle: {
    fontWeight: '800',
    fontSize: 18,
    color: '#333333',
    letterSpacing: 1,
  },
  prescriptionSectionStatValue: {
    marginTop: 5,
    fontWeight: '500',
    fontSize: 12,
    color: '#999999',
    textAlign: 'center',
  },
  prescriptionWeightCard: {
    marginHorizontal: 12,
    marginTop: 12,
    padding: 15,
    backgroundColor: '#FEFFFF',
    borderRadius: 12,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  prescriptionWeightTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  prescriptionWeightTagIcon: {
    width: 28,
    height: 16,
  },
  prescriptionWeightTagText: {
    marginLeft: 4,
    fontWeight: '500',
    fontSize: 13,
    color: '#666666',
  },
  prescriptionWeightBar: {
    marginTop: 20,
    marginBottom: 8,
    height: 8,
    gap: 3,
  },
  prescriptionWeightBarSeg: {
    height: 8,
  },
  prescriptionWeightBarSegFirst: {
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
  },
  prescriptionWeightBarSegLast: {
    borderTopRightRadius: 25,
    borderBottomRightRadius: 25,
  },
  prescriptionWeightLegendRow: {
    marginTop: 12,
    gap: 12,
  },
  prescriptionWeightLegendItem: {
    flex: 1,
    minWidth: 0,
  },
  prescriptionWeightDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
    flexShrink: 0,
  },
  prescriptionWeightLegendText: {
    width: 110,
    fontWeight: '500',
    fontSize: 13,
    color: '#333333',
  },
  prescriptionWeightLegendValue: {
    flexShrink: 0,
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },

  backImage1: {
    marginTop: 12,
    width: "100%",
    height: 50,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12
  },

  backImage1Text: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#333333"
  },
  prescriptionTypeCard: {
    marginHorizontal: 12,
    marginTop: 12,
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  prescriptionTypeCardFirst: {
    marginTop: 0,
  },
  prescriptionTypeIcon: {
    width: 18,
    height: 18,
  },
  prescriptionTypeTitleWrap: {
    marginLeft: 4,
    position: 'relative',
    alignSelf: 'flex-start',
  },
  prescriptionTypeUnderline: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 7,
    borderRadius: 25,
  },
  prescriptionTypeTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  prescriptionTypePercent: {
    marginLeft: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: 'rgba(109,146,94,0.12)',
    borderRadius: 25,
  },
  prescriptionTypePercentText: {
    fontWeight: '500',
    fontSize: 11,
    color: '#6D925E',
  },
  prescriptionTypeToggle: {
    width: 16,
    height: 16,
    flexShrink: 0,
  },
  prescriptionTypeBody: {
    marginTop: 8,
  },
  prescriptionTypeItem: {
    marginTop: 8,
    height: 66,
    padding: 15,
    backgroundColor: '#F6F8FB',
    borderRadius: 8,
  },
  prescriptionTypeItemIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  prescriptionTypeItemIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
  },
  prescriptionTypeItemInfo: {
    flex: 1,
    marginLeft: 12,
    justifyContent: 'center',
    minWidth: 0,
  },
  prescriptionTypeItemTitle: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  prescriptionTypeItemValue: {
    marginTop: 6,
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
  },
  prescriptionTimeline: {
    marginTop: 21,
  },
  prescriptionTimelineEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    paddingHorizontal: 16,
    backgroundColor: '#F6F8FB',
    borderRadius: 12,
  },
  prescriptionTimelineEmptyIcon: {
    width: 56,
    height: 56,
  },
  prescriptionTimelineEmptyTitle: {
    marginTop: 12,
    fontWeight: '600',
    fontSize: 15,
    color: '#666666',
    textAlign: 'center',
  },
  prescriptionTimelineEmptyDesc: {
    marginTop: 6,
    fontWeight: '500',
    fontSize: 13,
    lineHeight: 18,
    color: '#999999',
    textAlign: 'center',
  },
  prescriptionTimelineLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
  },
  prescriptionTimelineItem: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  prescriptionTimelineItemLast: {
    minHeight: 8,
  },
  prescriptionTimelineItemLastMain: {
    paddingBottom: 0,
  },
  prescriptionTimelineAxis: {
    width: 8,
    alignItems: 'center',
    marginRight: 12,
  },
  prescriptionTimelineDotWrap: {
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  prescriptionTimelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EE9C44',
  },
  prescriptionTimelineLine: {
    flex: 1,
    width: 1,
    marginTop: -11,
    marginBottom: -20,
    backgroundColor: 'rgba(19,17,65,0.1)',
  },
  prescriptionTimelineMain: {
    flex: 1,
    minWidth: 0,
    paddingBottom: 20,
  },
  prescriptionTimelineHeader: {
    marginBottom: 8,
  },
  prescriptionTimelineVersion: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
  },
  prescriptionTimelineActiveBadge: {
    marginLeft: 6,
    paddingHorizontal: 6,
    paddingVertical: 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  prescriptionTimelineActiveBadgeText: {
    fontWeight: 'bold',
    fontSize: 11,
    color: '#6D925E',
  },
  prescriptionTimelineTime: {
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
  },
  prescriptionTimelineCard: {
    paddingHorizontal: 12,
    paddingVertical: 15,
    backgroundColor: '#F6F8FB',
    borderRadius: 12,
  },
  prescriptionTimelineCardTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  prescriptionTimelineCardDesc: {
    marginTop: 6,
    fontWeight: '500',
    fontSize: 13,
    color: '#999999',
  },
  prescriptionDisclaimer: {
    marginHorizontal: 12,
    marginTop: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(109,146,94,0.06)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(109,146,94,0.3)',
  },
  prescriptionDisclaimerIcon: {
    width: 15,
    height: 15,
    marginTop: 2,
    flexShrink: 0,
  },
  prescriptionDisclaimerTextWrap: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    marginLeft: 6,
  },
  prescriptionDisclaimerText: {
    fontWeight: '500',
    fontSize: 13,
    color: '#666666',
    lineHeight: 20,
  },
});

export default styles;
