import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  body: { padding: 18, paddingTop: 2, paddingBottom: 40 },
  rowBox: {
    padding: 22,
    borderRadius: 8,
    marginTop: 16,
    backgroundColor: '#FFFFFF',
    shadowColor: AppTheme.primaryColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
  },
  dayTitleBtn: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  dayTitle: { fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, textAlign: 'center' },
  navIcon: { width: 24, height: 24 },
  navIconRight: { width: 24, height: 24, transform: [{ rotate: '180deg' }] },
  weekHead: { flexDirection: 'row', marginTop: 20 },
  weekCell: {
    flex: 1,
    height: 21,
    fontWeight: 400,
    fontSize: 14,
    color: AppTheme.textPrimary,
    lineHeight: 21,
    textAlign: 'center',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 8,
    overflow: 'hidden',
  },
  dash: { width: 5, height: 1, backgroundColor: 'rgba(153,153,153,0.17)' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: { width: '14.28%', height: 40, justifyContent: 'center', alignItems: 'center' },
  dayText: {
    fontWeight: 400,
    fontSize: 14,
    color: AppTheme.textPrimary,
    lineHeight: 21,
    textAlign: 'center',
  },
  dayTextOther: {
    fontWeight: 400,
    fontSize: 14,
    color: AppTheme.textSecondary,
    lineHeight: 21,
    textAlign: 'center',
  },
  dayInner: { width: 24, height: 24, justifyContent: 'center', alignItems: 'center' },
  daySelected: { backgroundColor: '#053A93', borderRadius: 20 },
  dayTextSelected: { fontWeight: 400, fontSize: 14, color: '#FFFFFF', textAlign: 'center' },
  dayDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FF8B07',
    marginTop: 2,
  },
  dayDotSelected: { backgroundColor: '#FFFFFF' },
  loadingBox: { marginTop: 24, alignItems: 'center' },
  emptyTimelineBox: { marginTop: 20, paddingVertical: 24, alignItems: 'center' },
  emptyTimelineText: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
  titleText: {
    marginTop: 24,
    fontWeight: 400,
    fontSize: 14,
    textAlign: 'center',
    color: '#999999',
  },
  timelineWrap: {
    marginTop: 20,
    position: 'relative',
  },
  exerciseSectionWrap: {
    marginBottom: 24,
  },
  exerciseRowSectionLast: {
    marginBottom: 0,
  },
  scheduledTimelineWrap: {
    position: 'relative',
  },
  axisLine: {
    position: 'absolute',
    left: 25.5,
    top: 25,
    bottom: 32,
    width: 1,
    backgroundColor: 'rgba(51,51,51,0.2)',
  },
  periodRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  periodRowAfternoon: {
    marginTop: 26,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  timelineRowGap: {
    marginBottom: 16,
  },
  timelineRowSectionLast: {
    marginBottom: 0,
  },
  timelineRowLast: {
    marginBottom: 0,
  },
  timeAxis: {
    width: 52,
    alignItems: 'center',
  },
  cardSide: {
    flex: 1,
    paddingLeft: 16,
  },
  periodText: {
    fontWeight: 500,
    fontSize: 18,
    color: '#333333',
    textAlign: 'center',
    lineHeight: 25,
    backgroundColor: AppTheme.backgroundColor,
    paddingHorizontal: 4,
  },
  timeSlot: {
    width: '100%',
    minHeight: 64,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  timePrefixText: {
    fontWeight: 400,
    fontSize: 12,
    color: '#999999',
    textAlign: 'center',
    lineHeight: 17,
    backgroundColor: AppTheme.backgroundColor,
    paddingHorizontal: 2,
    marginBottom: 2,
  },
  timeText: {
    fontWeight: 400,
    fontSize: 16,
    color: '#333333',
    textAlign: 'center',
    lineHeight: 22,
    backgroundColor: AppTheme.backgroundColor,
    paddingHorizontal: 4,
  },
  taskCardIcon: { width: 32, height: 32, marginRight: 12 },
  taskCard: {
    width: 280,
    maxWidth: '100%',
    height: 64,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 17,
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  taskCardTitle: {
    fontWeight: 500,
    fontSize: 16,
    color: '#333333',
  },
  taskCardMedicationType: {
    marginLeft: 8,
    fontWeight: 400,
    fontSize: 14,
    color: '#999999',
  },
  taskCardDesc: {
    marginTop: 4,
    fontWeight: 400,
    fontSize: 14,
    color: '#999999',
  },
  taskCardStatus: {
    marginLeft: 6,
    fontWeight: 400,
    fontSize: 14,
    color: '#999999',
  },
  taskCardStatusIconWrap: {
    width: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taskCardStatusCircleAction: {
    width: 13,
    height: 13,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: AppTheme.primaryColor,
  },
  taskCardStatusCircleTaken: {
    width: 13,
    height: 13,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'rgba(5,58,147,0.28)',
  },
  taskCardStatusCircleMuted: {
    width: 13,
    height: 13,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: 'rgba(153,153,153,0.35)',
  },
  taskCardStatusCheck: {
    position: 'absolute',
    top: 3,
    left: 2,
    fontSize: 16,
    lineHeight: 15,
    color: '#34B69F',
    fontWeight: '700',
  },
  taskCardStatusTaken: {
    color: '#6D925E',
  },
  taskCardStatusAction: {
    color: AppTheme.primaryColor,
  },
});

export default styles;
