import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    navBox: { marginTop: 16, marginLeft: 8, paddingHorizontal: 18, paddingBottom: 0 },
    navCol: { paddingHorizontal: 8 },
    navItemWrap: { position: 'relative', alignItems: 'center', paddingBottom: 12 },
    navText: { fontWeight: 400, fontSize: 16, color: "#999999", lineHeight: 22 },
    activeNavText: { color: AppTheme.primaryColor, fontWeight: 500, fontSize: 18, lineHeight: 24 },
    navIndicatorWrap: { position: 'absolute', left: 0, right: 0, bottom: 6, alignItems: 'center' },
    navIndicator: { width: 34, height: 10 },
    body: { padding: 18, paddingTop: 2, paddingBottom: 40 },
    sectionTitle: { marginLeft: 14, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary },
    medicationBox: {
        marginTop: 12,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        paddingHorizontal: 15,
        paddingTop: 11,
        paddingVertical: 16,
    },
    medicationTitleBox: { paddingBottom: 12 },
    medicationTime: { width: 22, height: 22, marginLeft: 9 },
    medicationTitle: { fontWeight: 500, fontSize: 18, color: "#333333", marginLeft: 8 },
    medicationTimeText: { fontWeight: 400, fontSize: 16, color: "#999999", marginLeft: 16 },
    medicationCF: { height: 20, backgroundColor: "rgba(5,58,147,0.14)", borderRadius: 10, paddingHorizontal: 7, marginLeft: 11 },
    medicationCFText: { fontWeight: 500, fontSize: 12, color: "#053A93" },
    medicationGR: { height: 20, backgroundColor: "rgba(52,182,159,0.12)", borderRadius: 10, paddingHorizontal: 7, marginLeft: 11 },
    medicationGRText: { fontWeight: 400, fontSize: 12, color: "#34B69F" },
    medicationInfo: { marginTop: 4, marginHorizontal: 9 },
    medicationLeftBox: { marginTop: 17 },
    medicationLeftTitle: { fontWeight: 500, fontSize: 16, color: "#000000" },
    medicationText: { marginTop: 4, fontWeight: 400, fontSize: 14, color: "#999999" },
    medicationStatusIconWrap: {
        width: 18,
        height: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    medicationStatusCircle: {
        width: 13,
        height: 13,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#053A93',
    },
    medicationStatusCircleTaken: {
        width: 13,
        height: 13,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'rgba(5,58,147,0.28)',
    },
    medicationStatusCheck: {
        position: 'absolute',
        top: 3,
        left: 2,
        fontSize: 16,
        lineHeight: 15,
        color: '#34B69F',
        fontWeight: '700',
    },
    medicationWfyText: {
        marginLeft: 6,
        fontWeight: '500',
        fontSize: 14,
        color: '#053A93',
    },
    medicationYfyText: {
        marginLeft: 6,
        fontWeight: '500',
        fontSize: 14,
        color: '#34B69F',
    },
    progressRing: { width: 48, height: 48, justifyContent: 'center', alignItems: 'center' },
    progressCanvas: { width: 48, height: 48, position: 'absolute' },
    progressText: { fontWeight: 500, fontSize: 12, color: '#FF8B07', lineHeight: 14 },
    colTitle: { fontWeight: 400, fontSize: 16, color: "#333333" },
    rowLine: { height: 1, backgroundColor: "#E8DED2" },
    typeItem: { height: 32, paddingHorizontal: 23, backgroundColor: "rgba(5,58,147,0.14)", borderRadius: 16 },
    typeItemActive: { backgroundColor: AppTheme.primaryColor },
    typeItemText: { fontWeight: 400, fontSize: 14, color: AppTheme.primaryColor },
    typeItemTextActive: { color: '#FFFFFF' },
    colIcon: { width: 14, height: 14 },
    tipCheckIcon: { width: 16, height: 16 },
    colText: { marginLeft: 8, fontWeight: 400, fontSize: 16, color: "#333333" },
    more: { marginTop: 15, fontWeight: 400, fontSize: 14, color: AppTheme.primaryColor },
    listBox: { marginTop: 12 },
    listItem: { marginBottom: 8 },
    listItemText: {
        fontWeight: 400,
        fontSize: 14,
        color: AppTheme.textSecondary
    },
    leftText: {
        fontWeight: 400,
        fontSize: 14,
        color: AppTheme.textSecondary,
    },
})

export default styles
