import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { padding: 12, paddingTop: 2, paddingBottom: 40 },
    sectionTitle: { fontWeight: "bold", fontSize: 16, color: AppTheme.textPrimary },
    cameraBoxRow: { marginTop: 17, gap: 12 },
    cameraBoxItem: {
        width: 99,
        height: 100,
    },
    cameraBoxDash: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        borderStyle: 'dashed',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    cameraBoxIcon: {
        width: 44,
        height: 44,
    },
    cameraBoxTitle: {
        marginTop: 10,
        fontWeight: '500',
        fontSize: 13,
        color: '#333333',
    },
    cameraIcon: { width: 99, height: 100 },
    cameraBoxText: { height: 19, fontWeight: 400, fontSize: 12, color: AppTheme.textPrimary },
    addBtn: { marginTop: 12, marginHorizontal: 18, height: 45, backgroundColor: "#053A93", borderRadius: 8 },
    addText: { height: 19, fontWeight: 500, fontSize: 16, color: "#FFFFFF" },
    bottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 15,
        paddingBottom: 40,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    bottomBarButtonLeft: {
        marginTop: 4,
        height: 50,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottomBarButtonImg: {
        width: 20,
        height: 20,
        marginRight: 4,
    },
    bottomBarButtonTextLeft: {
        fontWeight: '600',
        fontSize: 16,
        color: '#FFFFFF',
    },
    rowBox: { padding: 15, borderRadius: 8, marginTop: 12, backgroundColor: "#FFFFFF", shadowColor: AppTheme.primaryColor, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1 },
    rowTitle: { marginTop: 12, marginBottom: 10, height: 19, fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, lineHeight: 19 },
    typeSectionTitle: {
        marginTop: 22,
        fontWeight: '500',
        fontSize: 14,
        color: AppTheme.textPrimary,
        lineHeight: 19,
    },
    typeList: {
        marginTop: 18,
        columnGap: 8,
        rowGap: 10,
    },
    typeItem: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    typeItemActive: {
        backgroundColor: 'rgba(109,146,94,0.06)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    typeItemText: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    typeItemTextActive: {
        fontWeight: '500',
        fontSize: 14,
        color: '#6D925E',
    },
    tqText: { height: 19, fontWeight: 400, fontSize: 14, color: "#999999", lineHeight: 19, },
    arrowIcon: { width: 18, height: 18, marginLeft: 16 },
    inputBox: { height: 32, borderRadius: 24, backgroundColor: "#FFF", fontSize: 14, color: AppTheme.textPrimary },
    textareaBox: {
        marginTop: 12,
        height: 90,
        backgroundColor: '#F6F8FB',
        borderRadius: 8,
        padding: 15,
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        textAlignVertical: 'top',
    },
    ksList: {
        marginBottom: 12,
        flexGrow: 0,
    },
    ksListContent: {
        alignItems: 'center',
        columnGap: 8,
        paddingRight: 4,
    },
    ksItem: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    ksItemActive: {
        backgroundColor: 'rgba(109,146,94,0.06)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    ksItemText: {
        fontWeight: '500',
        fontSize: 13,
        color: '#333333',
    },
    ksItemTextActive: {
        color: '#6D925E',
    },
    uploadHint: { marginTop: 12, fontSize: 13, color: AppTheme.textSecondary },
    uploadHintText: { color: AppTheme.textPrimary },
    attachmentList: { marginTop: 12, flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    attachmentFileList: { gap: 12 },
    attachmentFileListGap: { marginTop: 4 },
    attachmentItem: { position: 'relative' },
    attachmentImg: { width: 60, height: 60, borderRadius: 8, backgroundColor: '#F5F5F5' },
    attachmentFileItem: {
        width: '100%',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#F5F5F5',
    },
    attachmentFileName: {
        flex: 1,
        marginLeft: 10,
        fontWeight: 400,
        fontSize: 14,
        color: AppTheme.textPrimary,
        lineHeight: 20,
    },
    attachmentRemove: {
        position: 'absolute',
        top: -6,
        right: -6,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.55)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    formRow: {
        width: '100%',
        height: 58,
        borderTopWidth: 1,
        borderTopColor: 'rgba(23,63,125,0.08)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        overflow: 'hidden',
    },
    formRowFirst: {
        marginTop: 20,
    },
    formSection: {
        marginTop: 20,
        borderTopWidth: 1,
        borderTopColor: 'rgba(23,63,125,0.08)',
        paddingTop: 16,
    },
    textareaTitle: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    formRowLabel: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        flexShrink: 0,

        textAlignVertical: 'center',
    },
    formRowValue: {
        flexDirection: 'row',
        alignItems: 'center',
        flexShrink: 1,
        marginLeft: 16,
    },
    formRowInput: {
        flex: 1,
        marginLeft: 16,
        paddingVertical: 0,
        textAlign: 'right',
        textAlignVertical: 'center',
        includeFontPadding: false,
        fontWeight: 'bold',
        fontSize: 14,
        color: '#999999',
    },
    dateValue: {
        fontWeight: 'bold',
        fontSize: 14,
        color: '#999999',
        lineHeight: 20,
        textAlign: 'right',
        textAlignVertical: 'center',
    },
    dateIcon: {
        width: 18,
        height: 18,
        marginLeft: 12,
    },

    // detail
    detailHeaderBox: {
        marginTop: 12,
        marginHorizontal: 12,
        borderRadius: 8,
        marginBottom: 8,
    },
    detailBlock: {
        marginHorizontal: 12,
        marginBottom: 20,
    },
    backImage1: { width: '100%', height: 50, marginTop: 12, borderTopLeftRadius: 12, borderTopRightRadius: 12 },
    backImage1Text: { fontWeight: 'bold', fontSize: 16, color: '#333333' },
    detailContentCard: {
        padding: 15,
        backgroundColor: '#FEFFFF',
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
    },
    detailSectionBar: {
        width: 4,
        height: 15,
        backgroundColor: '#6D925E',
        borderRadius: 25,
        marginRight: 6,
    },
    detailSectionTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#333333',
    },
    detailSectionContent: {
        marginTop: 15,
        fontWeight: '500',
        fontSize: 15,
        color: '#333333',
    },
    detailSectionDivider: {
        marginTop: 20,
        height: 1,
        backgroundColor: 'rgba(23,63,125,0.08)',
    },
    detailSectionNext: {
        marginTop: 20,
    },
    detailAttachmentBody: {
        marginTop: 15,
    },
    detailAttachmentList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    detailAttachmentImgWrap: {
        width: '31.2%',
        aspectRatio: 1,
        borderRadius: 8,
        overflow: 'hidden',
        backgroundColor: '#F6F8FB',
    },
    detailAttachmentImg: {
        width: '100%',
        height: '100%',
    },
    detailAttachmentFileList: {
        gap: 10,
    },
    detailAttachmentFileListGap: {
        marginTop: 10,
    },
    detailAttachmentFileItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 8,
        backgroundColor: '#F6F8FB',
    },
    detailAttachmentFileIcon: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: 'rgba(109,146,94,0.1)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    detailAttachmentFileIconImg: {
        width: 20,
        height: 20,
    },
    detailAttachmentFileInfo: {
        flex: 1,
        marginLeft: 10,
        marginRight: 8,
        minWidth: 0,
    },
    detailAttachmentFileName: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        lineHeight: 20,
    },
    detailAttachmentFileExt: {
        marginTop: 2,
        fontWeight: '500',
        fontSize: 11,
        color: '#6D925E',
    },
    detailAttachmentEmpty: {
        fontWeight: '500',
        fontSize: 15,
        color: '#999999',
    },
    detailAttachmentCount: {
        marginLeft: 6,
        fontWeight: '500',
        fontSize: 13,
        color: '#999999',
    },
    avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: AppTheme.primaryColor, alignItems: 'center', justifyContent: 'center' },
    avatarImg: { width: 64, height: 64, borderRadius: 32 },
    avatarLoading: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 32,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: { fontSize: 28, fontWeight: '700', color: '#fff' },
    name: { marginTop: 8, width: "100%", height: 27, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, lineHeight: 27, textAlign: "center" },
    userText: { height: 19, fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary, lineHeight: 19 },
    medicalBox: {
        marginTop: 17,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        paddingHorizontal: 25,
        paddingVertical: 16,
        marginBottom: 20
    },
    medicalTitle: { height: 19, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, lineHeight: 19 },
    medicalType: { height: 25, backgroundColor: 'rgba(5,58,147,0.13)', borderRadius: 4, marginLeft: 17, paddingHorizontal: 11 },
    medicalTypeText: { fontWeight: 400, fontSize: 12, color: AppTheme.primaryColor },
    medicalInfoBox: { marginTop: 12 },
    medicalCol: { width: "50%", paddingLeft: 17, paddingTop: 6, paddingBottom: 6 },
    medicalColLeft: { borderRightWidth: 1, borderRightColor: AppTheme.borderRgbColor },
    medicalLine: { borderTopWidth: 1, borderTopColor: AppTheme.borderRgbColor },
    medicalInfoTitle: { fontWeight: 500, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 21, },
    medicalInfoValue: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary, lineHeight: 21, },
    medicalImg: { width: 20, height: 20, marginRight: 8 }
})

export default styles
