import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { padding: 12, paddingTop: 2, paddingBottom: 40 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    rowBox: {
        padding: 15,
        borderRadius: 8,
        marginTop: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
    },
    formRow: {
        width: '100%',
        height: 54,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    formRowLabel: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        flexShrink: 0,
        lineHeight: 20,
    },
    formRowInput: {
        flex: 1,
        marginLeft: 16,
        paddingVertical: 0,
        textAlign: 'right',
        textAlignVertical: 'center',
        includeFontPadding: false,
        fontWeight: 'bold',
        fontSize: 14,
        color: '#333333',
    },
    formSection: {
        borderTopWidth: 1,
        borderTopColor: 'rgba(23,63,125,0.08)',
        paddingTop: 16,
        paddingBottom: 16,
    },
    formSectionFirst: {
        borderTopWidth: 0,
        paddingTop: 0,
        paddingBottom: 16,
    },
    formRowBorder: {
        borderTopWidth: 1,
        borderTopColor: 'rgba(23,63,125,0.08)',
    },
    sectionLabel: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        flexShrink: 0,
    },
    typeList: {
        marginTop: 14,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: 10,
    },
    typeListInline: {
        flex: 1,
        marginLeft: 16,
        flexWrap: 'nowrap',
        justifyContent: 'flex-end',
        alignItems: 'center',
        columnGap: 12,
    },
    typeItem: {
        width: '31.5%',
        paddingVertical: 7,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    statusItem: {
        minWidth: 64,
        paddingHorizontal: 16,
        paddingVertical: 4,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
    },
    typeItemActive: {
        backgroundColor: 'rgba(109,146,94,0.06)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    typeItemText: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    typeItemTextActive: {
        fontWeight: '500',
        fontSize: 14,
        color: '#6D925E',
    },
    statusRow: {
        width: '100%',
        height: 54,
        borderTopWidth: 1,
        borderTopColor: 'rgba(23,63,125,0.08)',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    bottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 15,
        paddingBottom: 40,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    bottomBarButton: {
        marginTop: 4,
        height: 50,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottomBarButtonImg: {
        width: 20,
        height: 20,
        marginRight: 4,
    },
    bottomBarButtonText: {
        fontWeight: '600',
        fontSize: 16,
        color: '#FFFFFF',
    },
});

export default styles;
