import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { paddingHorizontal: 12, paddingTop: 2, paddingBottom: 14 },
    bodyEmpty: {
        flexGrow: 1,
        paddingHorizontal: 18,
        paddingTop: 2,
        paddingBottom: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    emptyWrap: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyImage: {
        width: 120,
        height: 80,
    },
    emptyText: {
        marginTop: 25,
        fontWeight: 'bold',
        fontSize: 14,
        color: '#333333',
        textAlign: 'center',
    },
    avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: AppTheme.primaryColor, alignItems: 'center', justifyContent: 'center' },
    avatarImg: { width: 64, height: 64, borderRadius: 32 },
    avatarLoading: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        borderRadius: 32,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarText: { fontSize: 28, fontWeight: '700', color: '#fff' },
    name: { marginTop: 8, width: "100%", height: 27, fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary, lineHeight: 27, textAlign: "center" },
    sectionBox: { marginTop: 12 },
    sectionTitle: { fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary },
    more: { fontWeight: 500, fontSize: 13, color: '#666666' },
    editIcon: { width: 18, height: 18 },
    infoBox: {
        marginTop: 10,
        padding: 15,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FEFFFF",
        borderRadius: 8,
    },
    userBox: {
        marginTop: 12,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FEFFFF",
        borderRadius: 8,
    },
    userInfoBox: {
        marginTop: 25,
        marginBottom: 30
    },
    userEditIcon: {
        width: 25,
        height: 25,
        marginTop: -10,
    },
    infoItem: { height: 50, paddingHorizontal: 15, borderTopWidth: 1, borderTopColor: AppTheme.borderRgbColor },
    infoItemLabel: { fontWeight: 500, fontSize: 14, color: AppTheme.textSecondary },
    infoItemValue: { textAlign: "right", fontWeight: 500, fontSize: 14, color: AppTheme.textPrimary },
    allergyItemLeft: { flexShrink: 0 },
    allergySummaryText: { flex: 1, marginLeft: 12, minWidth: 0, color: '#999999' },
    allergySummaryActive: { color: '#6D925E' },
    infoInput: {
        flex: 1,
        marginLeft: 12,
        alignSelf: 'stretch',
        textAlign: 'right',
        textAlignVertical: 'center',
        includeFontPadding: false,
        fontWeight: 500,
        fontSize: 14,
        color: AppTheme.textPrimary,
        paddingVertical: 0,
    },
    infoPlaceholder: { color: AppTheme.textSecondary },
    fieldBlock: {
        paddingHorizontal: 15,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: AppTheme.borderRgbColor,
    },
    chipRow: { marginTop: 10, gap: 8 },
    familyItem: { marginTop: 6, height: 66, backgroundColor: "#F6F8FB", borderRadius: 8, padding: 15, overflow: 'hidden' },
    familyItemRow: { flexDirection: 'row', alignItems: 'center' },
    imgBox: { width: 44, height: 44, borderRadius: 22, marginRight: 12, backgroundColor: "#EBF0FB" },
    imgItem: { width: 24, height: 24 },
    familyItemImgBox: {
        width: 36,
        height: 36,
        borderRadius: 18,
        marginRight: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        overflow: 'hidden',
    },
    familyItemImg: {
        width: 36,
        height: 36,
    },
    familyItemContent1: { marginLeft: 6 },
    familyItemName: { fontWeight: "bold", fontSize: 14, color: AppTheme.textPrimary },
    familyItemRelation: { marginTop: 4, height: 19, fontWeight: 400, fontSize: 12, color: "#999" },
    familyItemRelation1: { marginTop: 2, height: 19, fontWeight: 400, fontSize: 14, color: "#999" },
    addBtn: { height: 45, backgroundColor: AppTheme.primaryColor, marginHorizontal: 18, borderRadius: 8, marginTop: 12 },
    addText: { height: 19, fontWeight: 500, fontSize: 16, color: "#FFFFFF" },
    bottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 15,
        paddingBottom: 40,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    bottomBarButtonLeft: {
        marginTop: 4,
        height: 50,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottomBarButtonImg: {
        width: 20,
        height: 20,
        marginRight: 4,
    },
    bottomBarButtonTextLeft: {
        fontWeight: '600',
        fontSize: 16,
        color: '#FFFFFF',
    },
    emergencyText: { marginTop: 12, fontWeight: 400, fontSize: 12, color: "#999999" },
    jzBox: { height: 19, backgroundColor: "rgba(102,202,152,0.13)", borderRadius: 4, paddingHorizontal: 9, marginLeft: 10 },
    jzText: { fontWeight: 500, fontSize: 12, color: "#66CA98" },
    familyAuthText: { fontWeight: 400, fontSize: 12, color: AppTheme.primaryColor, marginRight: 12 },
    familyItemTime: {
        fontWeight: "bold",
        fontSize: 12,
        color: "#333333",
    },
    familyItemContent: { flex: 1, minWidth: 0, overflow: 'hidden' },
    infoItemValue1: {
        marginTop: 4,
        fontWeight: 500,
        fontSize: 14,
        color: "#999999",
        flexShrink: 1,
    },



    // caseNotes
    topBox: { paddingHorizontal: 18, paddingTop: 19 },
    inputBox: {
        height: 38,
        borderRadius: 25,
        backgroundColor: '#FFFFFF',
        paddingLeft: 14,
        paddingRight: 16,
    },
    inputIcon: { width: 15, height: 15, flexShrink: 0 },
    inputText: {
        flex: 1,
        marginLeft: 8,
        paddingVertical: 0,
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    inputDivider: {
        width: 1,
        height: 12,
        backgroundColor: '#E5E5E5',
        marginRight: 15,
        flexShrink: 0,
    },
    inputSearchBtn: {
        fontWeight: 'bold',
        fontSize: 14,
        color: '#6D925E',
    },
    navBox: { marginTop: 16, alignItems: 'flex-start' },
    navCol: { paddingHorizontal: 8 },
    navItemWrap: { alignItems: 'center' },
    navText: {
        height: 24,
        lineHeight: 24,
        fontWeight: '500',
        fontSize: 14,
        color: '#666666',
        textAlign: 'center',
        includeFontPadding: false,
        textAlignVertical: 'top',
    },
    activeNavText: { fontWeight: 'bold', fontSize: 14, color: '#666666' },
    navIndicator: {
        marginTop: 4,
        width: 20,
        height: 3,
        backgroundColor: '#6D925E',
        borderRadius: 25,
    },
    swipeRow: { marginTop: 12, borderRadius: 16, shadowColor: AppTheme.primaryColor, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 3 },
    swipeAction: { position: 'absolute', top: 0, right: 0, bottom: 0, width: 72, zIndex: 0 },
    swipeForeground: { width: '100%', zIndex: 1, backgroundColor: '#FFF', borderRadius: 16 },
    swipeDeleteBtn: { flex: 1, width: 72, justifyContent: 'center', alignItems: 'center' },
    swipeDeleteText: { color: '#FFFFFF', fontSize: 15, fontWeight: '500' },
    caseBox: { padding: 15, backgroundColor: '#FFF', shadowColor: AppTheme.primaryColor, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12 },
    caseTitleWrap: {
        flex: 1,
        minWidth: 0,
        marginRight: 8,
    },
    caseTitle: {
        flexShrink: 1,
        fontWeight: 'bold',
        fontSize: 15,
        color: '#333333',
    },
    caseTypeTag: {
        marginLeft: 6,
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 4,
        borderWidth: 1,
        flexShrink: 0,
    },
    caseTypeTagText: {
        fontWeight: 'bold',
        fontSize: 11,
    },
    caseTime: {
        fontWeight: '500',
        fontSize: 13,
        color: '#999999',
        flexShrink: 0,
    },
    caseLineWrap: {
        marginTop:16,
        height: 1,
        overflow: 'hidden',
    },
    caseLine: {
        borderStyle: 'dashed',
        borderWidth: 1,
        borderColor: 'rgba(23,63,125,0.08)',
        marginTop: -1,
    },
    caseContentBox: { marginTop: 15 },
    caseContentText: {
        fontSize: 16,
    },
    caseContentTextSecond: {
        marginTop: 8,
    },
    caseContentLabel: {
        fontWeight: '500',
        fontSize: 16,
        color: '#666666',
    },
    caseContentValue: {
        fontWeight: '500',
        fontSize: 16,
        color: '#333333',
    },



    // editPage
    tipText: { fontWeight: 400, marginTop: 8, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 21 },
    arrowRight: { width: 19, height: 19, marginLeft: 16 },
    unitText: { fontWeight: 500, fontSize: 14, color: AppTheme.textSecondary, marginLeft: 16 },
    chipGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start' },
    wrapChipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
    chipItem: { width: '31%', marginRight: '3.5%', paddingHorizontal: 0, alignItems: 'center', justifyContent: 'center' },
    chipItemLastInRow: { marginRight: 0 },
    choiceChip: {
        marginTop: 10,
        height: 33,
        paddingHorizontal: 30,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    choiceChipInline: { marginTop: 0 },
    choiceChipWrap: { paddingHorizontal: 16 },
    choiceChipActive: {
        backgroundColor: 'rgba(109,146,94,0.12)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    choiceChipText: {
        fontWeight: '500',
        fontSize: 14,
        color: AppTheme.textPrimary,
    },
    choiceChipTextActive: {
        fontWeight: 'bold',
        color: AppTheme.primaryColor,
    },
    fieldMultilineInput: {
        marginTop: 10,
        minHeight: 72,
        fontWeight: 500,
        fontSize: 14,
        color: AppTheme.textPrimary,
        paddingVertical: 0,
        textAlign: 'left',
    },
})

export default styles
