import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    scroll: { padding: 18, paddingTop: 0, paddingBottom: 40 },
    sectionBox: {
        marginTop: 8,
        backgroundColor: '#FEFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        borderRadius: 8,
        paddingHorizontal: 18,
        paddingVertical: 16,
    },
    rowLine: { height: 1, backgroundColor: '#E7EAEB', width: '100%' },
    settingRow: {
        height: 62,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sectionTitle: { marginTop: 18, fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary, lineHeight: 19 },
    sectionDesc: { marginTop: 6, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 20 },
    optionBox: {
        width: '30%',
        height: 33,
        paddingHorizontal: 30,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    optionBoxThird: {
        width: '31%',
        height: 33,
        marginBottom: 10,
        paddingHorizontal: 6,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    optionRowWrap: { width: '100%' },
    optionBoxActive: {
        backgroundColor: 'rgba(109,146,94,0.12)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    optionText: { fontWeight: 500, fontSize: 14, color: AppTheme.textPrimary },
    optionTextSm: { fontWeight: 500, fontSize: 12, color: AppTheme.textPrimary, textAlign: 'center' },
    optionTextActive: { fontWeight: 'bold', color: AppTheme.primaryColor },
    previewBox: { marginTop: 18, padding: 16, borderRadius: 8, backgroundColor: 'rgba(109,146,94,0.08)' },
    previewLabel: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, marginBottom: 8 },
    previewText: { fontWeight: 400, color: AppTheme.textPrimary, lineHeight: 19 },
    imgBox: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(109,146,94,0.12)' },
    imgItem: { width: 22, height: 22 },
    itemText: { marginLeft: 12, fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, },
    rowTitle: { fontWeight: 400, fontSize: 16, color: "#333333" },
    switch: { width: 44, height: 22 },
});

export default styles;
