import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    scroll: { padding: 12, paddingTop: 0, paddingBottom: 40 },
    sectionBox: {
        marginTop: 8,
        backgroundColor: '#FEFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        borderRadius: 8,
        paddingHorizontal: 18,
        paddingVertical: 16,
    },
    rowLine: { height: 1, backgroundColor: '#E7EAEB', width: '100%' },
    settingRow: {
        paddingVertical: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
    },
    settingRowMulti: {
        paddingVertical: 14,
    },
    settingLeft: {
        flex: 1,
        flexShrink: 1,
        minWidth: 0,
        marginRight: 21,
        flexDirection: 'row',
        alignItems: 'center',
    },
    settingLeftText: {
        flex: 1,
        flexShrink: 1,
        minWidth: 0,
    },
    switchWrap: {
        flexGrow: 0,
        flexShrink: 0,
        width: 51,
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    sectionTitle: { marginTop: 18, fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary, lineHeight: 19 },
    sectionDesc: { marginTop: 6, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 20 },
    optionBox: {
        width: '30%',
        height: 33,
        paddingHorizontal: 30,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    optionBoxThird: {
        width: '31%',
        height: 33,
        marginBottom: 10,
        paddingHorizontal: 6,
        backgroundColor: '#F6F7FA',
        borderRadius: 8,
        borderWidth: 2,
        borderColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    optionRowWrap: { width: '100%' },
    optionBoxActive: {
        backgroundColor: 'rgba(109,146,94,0.12)',
        borderColor: 'rgba(109,146,94,0.3)',
    },
    optionText: { fontWeight: 500, fontSize: 14, color: AppTheme.textPrimary },
    optionTextSm: { fontWeight: 500, fontSize: 12, color: AppTheme.textPrimary, textAlign: 'center' },
    optionTextActive: { fontWeight: 'bold', color: AppTheme.primaryColor },
    previewBox: { marginTop: 18, padding: 16, borderRadius: 8, backgroundColor: 'rgba(109,146,94,0.08)' },
    previewLabel: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, marginBottom: 8 },
    previewText: { fontWeight: 400, color: AppTheme.textPrimary, lineHeight: 19 },
    fontPreviewChat: {
        marginTop: 0,
        paddingHorizontal: 6,
    },
    fontPreviewRightWrap: {
        marginTop: 18,
        alignItems: 'flex-end',
    },
    fontPreviewRightBubble: {
        maxWidth: '85%',
        minHeight: 56,
        backgroundColor: '#6D925E',
        borderTopLeftRadius: 18,
        borderTopRightRadius: 4,
        borderBottomRightRadius: 18,
        borderBottomLeftRadius: 18,
        padding: 16,
        justifyContent: 'center',
    },
    fontPreviewRightText: {
        fontWeight: '500',
        fontSize: 16,
        color: '#FFFFFF',
    },
    fontPreviewLeftWrap: {
        marginTop: 22,
        alignItems: 'flex-start',
    },
    fontPreviewLeftBubble: {
        maxWidth: '85%',
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 4,
        borderTopRightRadius: 18,
        borderBottomRightRadius: 18,
        borderBottomLeftRadius: 18,
        padding: 16,
    },
    fontPreviewLeftText: {
        fontWeight: '500',
        fontSize: 16,
        lineHeight: 24,
        color: '#333333',
    },
    fontPreviewOptions: {
        marginTop: 24,
    },
    fontPreviewChatArea: {
        flex: 1,
    },
    fontSizeSliderSection: {
        paddingHorizontal: 40,
        paddingBottom: 8,
    },
    fontSizeSliderWrap: {
        width: '100%',
    },
    fontSizeSliderLabels: {
        position: 'relative',
        width: '100%',
        marginTop: 17,
        marginBottom: 40,
        height: 22,
    },
    fontSizeSliderLabelWrap: {
        position: 'absolute',
        top: 0,
        width: 64,
        marginLeft: -32,
        alignItems: 'center',
    },
    fontSizeSliderLabel: {
        fontWeight: '500',
        fontSize: 16,
        color: '#999999',
        textAlign: 'center',
    },
    fontSizeSliderLabelActive: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#000000',
    },
    fontSizeSliderTrackHit: {
        height: 32,
        justifyContent: 'center',
    },
    fontSizeSliderTrack: {
        height: 6,
        backgroundColor: '#EAEAEA',
        borderRadius: 3,
        position: 'relative',
        justifyContent: 'center',
    },
    fontSizeSliderTick: {
        position: 'absolute',
        top: (6 - 15) / 2,
        width: 4,
        height: 15,
        backgroundColor: '#EAEAEA',
        borderRadius: 25,
    },
    fontSizeSliderThumb: {
        position: 'absolute',
        top: (32 - 24) / 2,
        width: 24,
        height: 24,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
        borderWidth: 4,
        borderColor: '#FFFFFF',
    },
    fontSizeBottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 15,
        paddingBottom: 40,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    fontSizeConfirmBtn: {
        marginTop: 4,
        height: 50,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    fontSizeConfirmText: {
        fontWeight: '600',
        fontSize: 16,
        color: '#FFFFFF',
    },
    imgBox: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(109,146,94,0.12)' },
    imgItem: { width: 22, height: 22, flexShrink: 0 },
    itemText: { marginLeft: 12, fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary },
    itemTextSmall: {
        marginLeft: 12,
        marginTop: 4,
        lineHeight: 20,
        fontWeight: 400,
        fontSize: 14,
        color: AppTheme.textSecondary,
        flexShrink: 1,
    },
    rowTitle: { fontWeight: 400, fontSize: 16, color: "#333333" },
    switch: { width: 44, height: 22 },
    settingArrowHit: {
        minWidth: 44,
        minHeight: 44,
        marginRight: -12,
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'flex-end',
        flexShrink: 0,
    },
    settingArrowIcon: {
        width: 8,
        height: 13,
    },
    acceptAiSheetHost: {
        backgroundColor: 'transparent',
        overflow: 'visible',
        shadowOpacity: 0,
        elevation: 0,
    },
    acceptAiWrap: {
        width: '100%',
        position: 'relative',
        overflow: 'visible',
    },
    acceptAiHero: {
        width: 118,
        height: 125,
        position: 'absolute',
        top: -63,
        left: '50%',
        marginLeft: -59,
        zIndex: 2,
    },
    acceptAiSheet: {
        width: '100%',
        borderTopLeftRadius: 18,
        borderTopRightRadius: 18,
        paddingTop: 18,
        paddingHorizontal: 20,
        alignItems: 'center',
        overflow: 'visible',
    },
    acceptAiTopImg: {
        width: 310,
        height: 17
    },
    acceptAiTitle: {
        marginTop: 48,
        marginBottom: 4,
        fontWeight: '700',
        fontSize: 18,
        color: AppTheme.textPrimary,
        lineHeight: 26,
        textAlign: 'center',
    },
    acceptAiScroll: {
        width: '100%',
        maxHeight: 360,
        alignSelf: 'stretch',
    },
    acceptAiScrollContent: {
        paddingBottom: 8,
        paddingRight: 4,
    },
    acceptAiDesc: {
        marginTop: 4,
        fontWeight: '500',
        fontSize: 14,
        color: '#666666',
        lineHeight: 20,
        textAlign: 'left',
        width: '100%',
    },
    acceptItem: {
        marginTop: 12,
        width: '100%',
    },
    acceptAiDataList: {
        paddingLeft: 68,
        marginTop: 8,
        marginBottom: 12,
        width: '100%',
    },
    acceptIcon: {
        width: 18,
        height: 18,
        flexShrink: 0,
    },
    acceptText: {
        fontWeight: 500,
        fontSize: 15,
        color: "#333333",
        marginLeft: 8,
        textAlign: 'left',
        flexShrink: 1,
    },
    acceptAiBtnRow: {
        marginTop: 20,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 12,
    },
    acceptAiCancelBtn: {
        flex: 1,
        height: 44,
        borderRadius: 25,
        backgroundColor: '#F6F8FB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    acceptAiCancelText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: "#333333",
    },
    acceptAiConfirmBtnWrap: {
        flex: 1,
        height: 44,
        borderRadius: 25,
    },
    acceptAiConfirmBtn: {
        width: '100%',
        height: 44,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
    },
    acceptAiConfirmText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#FFFFFF',
    },
});

export default styles;
