import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { padding: 18, paddingTop: 2, paddingBottom: 40 },
    medicalBox: {
        marginTop: 17,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FFFFFF",
        borderRadius: 8,
        paddingHorizontal: 15,
        paddingVertical: 13,
    },
    medicalTitle: { fontWeight: 500, marginTop: 14, fontSize: 18, color: AppTheme.textPrimary },
    medicalType: { height: 25, backgroundColor: 'rgba(5,58,147,0.13)', borderRadius: 4, marginLeft: 17, paddingHorizontal: 11 },
    medicalTypeText: { fontWeight: 400, fontSize: 12, color: AppTheme.primaryColor },
    medicalInfoBox: { marginTop: 12 },
    medicalCol: { width: "50%", minWidth: 0, flexShrink: 1, paddingLeft: 17, paddingTop: 6, paddingBottom: 6, overflow: 'hidden' },
    medicalInfoValueScroll: { width: '100%', height: 21 },
    medicalInfoValueText: { flexShrink: 0 },
    medicalColLeft: { borderRightWidth: 1, borderRightColor: AppTheme.borderRgbColor },
    medicalLine: { borderTopWidth: 1, borderTopColor: AppTheme.borderRgbColor },
    medicalInfoTitle: { fontWeight: 500, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 21 },
    medicalInfoValue: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary, lineHeight: 21, marginRight: 10 },
    leftTitle: { fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary },
    leftTitleDel: { color: "#666666", textDecorationLine: 'line-through' },
    rightText: { fontWeight: 400, marginTop: 14, fontSize: 14, color: "#999999", lineHeight: 21 },
    leftText: { marginTop: 6, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    progressRing: { width: 48, height: 48, justifyContent: 'center', alignItems: 'center' },
    progressCanvas: { width: 48, height: 48, position: 'absolute' },
    progressText: { fontWeight: 500, fontSize: 12, color: '#053A93', lineHeight: 14 },
    medicalStatus: { paddingHorizontal: 18, height: 33, borderRadius: 17, backgroundColor: "rgba(5,58,147,0.14)" },
    progressBtnWrap: { position: 'relative', alignSelf: 'flex-start' },
    progressBtnCanvas: { position: 'absolute', left: 0, top: 0, right: 0, bottom: 0 },

    statusIcon: { width: 22, height: 22 },
    statusText: { marginLeft: 3, fontWeight: 500, fontSize: 16, color: AppTheme.primaryColor },
    ywcText: { fontWeight: 500, fontSize: 16, color: "#66CA98", marginRight: 16 },
    weekHead: { flexDirection: 'row' },
    weekCell: { flex: 1, height: 21, fontWeight: 400, fontSize: 14, color: '#333333', lineHeight: 21, textAlign: 'center' },
    weekDayRow: { flexDirection: 'row', marginTop: 8 },
    weekDayCell: { flex: 1, height: 36, alignItems: 'center', justifyContent: 'center' },
    weekDayCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        position: "relative"
    },
    weekDayCompleted: { backgroundColor: '#00C950' },
    weekDayIncomplete: { backgroundColor: '#FE9A00' },
    weekDayToday: { backgroundColor: '#053A93' },
    weekDayBadgeText: { fontWeight: 400, fontSize: 14, color: '#FFFFFF', textAlign: 'center' },
    weekDayTodayText: { position: "absolute", fontWeight: 400, fontSize: 14, color: AppTheme.primaryColor, bottom: -16 },
    weekDayPlainText: { fontWeight: 400, fontSize: 14, color: '#333333', textAlign: 'center' },
    divider: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, marginBottom: 8, overflow: 'hidden' },
    dash: { width: 5, height: 1, backgroundColor: 'rgba(153,153,153,0.17)' },
    statRow: { marginTop: 17, gap: 10 },
    statBox: { flex: 1, marginTop: 0 },
    allBtn: { marginTop: 14, fontWeight: 400, fontSize: 14, color: "#053A93" },
    statTitle: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary },
    statValue: { marginTop: 4, fontWeight: 500, fontSize: 16, color: AppTheme.primaryColor },
})

export default styles
