import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  scroll: { padding: 12, paddingTop: 8, paddingBottom: 40, flex: 1 },
  topBox: { marginTop: 10, paddingHorizontal: 22 },
  topBoxImage: { width: 15, height: 15, marginRight: 3 },
  topBoxText: { fontSize: 13, fontWeight: 500, color: AppTheme.primaryColor },
  topNameBox: { marginTop: 27, position: 'relative', minHeight: 70 },
  topNameText: { fontWeight: 'bold', fontSize: 22, color: "#000000" },
  containerBox: { marginLeft: 8, height: 22, paddingHorizontal: 6, backgroundColor: "#FFFFFF", borderRadius: 25, borderWidth: 1, borderColor: "#6D925E" },
  topNameImage: { width: 12, height: 12, marginRight: 3 },
  cfText: { fontWeight: 'bold', fontSize: 12, color: "#6D925E" },
  rightImg: { width: 70, height: 70, position: 'absolute', right: 0, top: 0 },
  topInfoBox: { marginTop: 12 },
  topInfoText: { fontWeight: 500, fontSize: 12, color: "#666666" },
  brBox: { height: 17, paddingHorizontal: 4, backgroundColor: "#6D925E", borderRadius: 4, marginRight: 6 },
  brText: { fontWeight: "bold", fontSize: 12, color: "#FFFFFF" },
  navBox: { marginHorizontal: 12, marginTop: 20, height: 40, padding: 3, backgroundColor: "rgba(109,146,94,0.12)", borderRadius: 25, gap: 6 },
  navItem: { flex: 1, height: "100%", borderRadius: 25, paddingHorizontal: 12 },
  activeNavItem: { backgroundColor: "#FFF" },
  navIcon: { width: 18, height: 18, marginRight: 3 },
  navText: { fontWeight: 500, fontSize: 14, color: AppTheme.textPrimary },
  activeNavText: { fontWeight: "bold" },
  emptyPrescription: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  emptyPrescriptionIcon: {
    marginTop: -60,
    width: 80,
    height: 80,
  },
  emptyPrescriptionText: {
    marginTop: 25,
    fontWeight: '500',
    fontSize: 14,
    color: '#999999',
    textAlign: 'center',
  },
  calendarBox: { marginTop: 18, height: 64, paddingHorizontal: 13 },
  calendarCol: { width: 38, height: "100%", borderRadius: 25, backgroundColor: "transparent" },
  calendarColActive: { backgroundColor: "rgba(109,146,94,0.12)" },
  calendarTitle: { fontWeight: "bold", fontSize: 13, color: "#666666", marginTop: 12, textAlign: "center" },
  calendarTitleActive: { fontWeight: "bold", fontSize: 13, color: AppTheme.primaryColor, marginTop: 12, textAlign: "center" },
  calendarSubtitle: { fontWeight: 500, fontSize: 18, marginTop: 5, color: AppTheme.textPrimary, textAlign: "center" },
  calendarSubtitleActive: { fontWeight: 500, fontSize: 18, marginTop: 5, color: AppTheme.primaryColor, textAlign: "center" },
  calendarImage: { width: 22, height: 22, marginTop: 5, margin: "auto" },
  calendarContent: {
    padding: 15,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 12,
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  calendarContentTitle: { fontWeight: "bold", fontSize: 16, color: AppTheme.textPrimary },
  calendarContentProgress: { marginVertical: 21 },
  valueBox: { flex: 1 },
  valueTitle: { fontWeight: 500, fontSize: 12, color: AppTheme.textSecondary },
  valueText: { fontWeight: 500, fontSize: 22, color: AppTheme.textPrimary, marginTop: 6 },
  lineBox: { height: 1, backgroundColor: "rgba(23,63,125,0.08)" },
  calendarContentProgressRing: { width: 120, height: 120, position: "relative" },
  calendarContentTitleBox: { position: "absolute", width: 120, height: 120 },
  title1: { marginTop: 30, fontWeight: 500, fontSize: 12, color: AppTheme.textSecondary, textAlign: "center" },
  title2: { marginTop: 4, fontWeight: "bold", fontSize: 25, color: AppTheme.textPrimary, textAlign: "center" },
  title3: { marginTop: 4, fontWeight: 500, fontSize: 11, textAlign: "center", color: AppTheme.textSecondary },
  dietListBox: { marginTop: 15 },
  dietList: { width: 77 },
  dietListImage: { width: 18, height: 18, marginRight: 3 },
  dietListText: { fontWeight: 500, fontSize: 13, color: "#999999", lineHeight: 18 },
  dietListLine: { backgroundColor: "#ecedf1", height: 6, marginTop: 7, borderRadius: 3 },
  dietListLineInner: { height: 6, borderRadius: 3 },
  btmBox: { marginTop: 8, fontWeight: "bold", fontSize: 13, color: "#333333" },
  btmBoxText: { fontSize: 13, color: "#999999", lineHeight: 18 },
  calendarContentSubtitle: { fontWeight: 500, fontSize: 13, color: "#666666" },
  dietMapBox: { marginTop: 20, height: 45 },
  mapImg: { width: 45, height: 45, marginRight: 12 },
  mapCenBox: { flex: 1 },
  mapTitle: { fontWeight: "bold", fontSize: 14, color: "#333333" },
  mapCenBoxList: { marginTop: 6 },
  mapBor: { width: 6, height: 6, marginRight: 3, borderRadius: 3, backgroundColor: "#6D925E" },
  mapText: { fontWeight: "bold", fontSize: 12, color: "#999999", marginRight: 6 },
  mapValue: { fontWeight: "bold", fontSize: 13, color: "#999999" },
  mapValueText: { fontWeight: "bold", fontSize: 13, color: "#6D925E" },
  actualEatBox: {
    borderRadius: 12,
    marginTop: 16,
    padding: 15,
    backgroundColor: '#F6F8FB',
  },
  actualEatTitle: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#333333',
  },
  actualEatValue: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#6D925E',
  },
  actualEatUnit: {
    fontWeight: 'bold',
    fontSize: 13,
    color: '#6D925E',
  },
  actualEatFoodRow: {
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#FFF",
    marginTop: 12,
    alignItems: 'center',
  },
  actualEatFoodImg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: '#FFFFFF',
  },
  actualEatFoodInfo: {
    flex: 1,
    paddingRight: 8,
  },
  actualEatFoodName: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#333333',
    marginBottom: 4,
  },
  actualEatFoodMeta: {
    fontSize: 12,
    color: '#999999',
  },
  actualEatDelIcon: {
    width: 28,
    height: 28,
  },
  actualEatSummaryRow: {
    marginTop: 12,
  },
  actualEatSummaryText: {
    fontSize: 12,
    color: '#999999',
    flexShrink: 1,
    paddingRight: 8,
  },
  actualEatDiffBadge: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  actualEatDiffText: {
    marginLeft: 2,
    fontWeight: 'bold',
    fontSize: 14,
    color: '#6D925E',
  },
  btnBox: { marginTop: 20, height: 48, backgroundColor: "#F6F8FB", borderRadius: 12 },
  btnImg: { width: 16, height: 16, marginRight: 6 },
  btnText: { fontWeight: 500, fontSize: 14, color: "#333333" },
  bottomBar: {
    width: '100%',
    paddingHorizontal: 15,
    paddingTop: 17,
    backgroundColor: '#FEFEFE',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    shadowColor: '#B4C9FF',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 4,
    elevation: 3,
  },
  bottomBarButtonLeft: { flex: 2, height: 46, marginRight: 12, backgroundColor: '#6D925E', borderRadius: 12, borderWidth: 1, borderColor: '#6D925E' },
  bottomBarButtonLeftDisabled: {
    backgroundColor: 'rgba(109,146,94,0.45)',
    borderColor: 'rgba(109,146,94,0.45)',
  },
  bottomBarButtonRight: { flex: 1, height: 46, backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: '#6D925E' },
  btnImgSize: { width: 20, height: 20, marginRight: 4 },
  bottomBarButtonTextLeft: { fontWeight: 'bold', fontSize: 16, color: '#FFFFFF' },
  bottomBarButtonTextRight: { fontWeight: 'bold', fontSize: 16, color: '#6D925E' },


  backImageBox: {
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  backImage: {
    marginHorizontal: 12,
    overflow: "hidden",
    marginTop: 6, borderRadius: 12, padding: 15,
  },
  kcalBox: { marginTop: 14 },
  kcalValue: { fontWeight: "bold", fontSize: 30, color: AppTheme.textPrimary },
  kcalText: { fontWeight: 500, fontSize: 14, marginLeft: 2, marginTop: 10, color: AppTheme.textSecondary },
  kcalInfoBox: {
    marginTop: 10,
    minHeight: 39,
    alignItems: 'flex-start',
    backgroundColor: 'rgba(254,248,225,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(238,156,68,0.3)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  kcalInfoIcon: { width: 15, height: 15, marginRight: 6, marginTop: 1 },
  kcalInfoText: { flex: 1, flexShrink: 1, fontWeight: 500, fontSize: 12, color: '#C98A41', lineHeight: 18 },
  rowScroll: {
    marginTop: 15
  },
  colBox: {
    paddingTop: 12,
    paddingBottom: 12,
    width: 139,
    backgroundColor: "#F6F8FB",
    borderRadius: 8,
    marginRight: 12
  },
  colValueBox: {
    position: "relative"
  },
  colValue: {
    position: "absolute",
    fontWeight: "bold",
    fontSize: 12,
    color: "#333333",
  },
  colValueText: {
    fontWeight: "bold",
    fontSize: 13,
    color: "#999999",
  },
  colImg: {
    width: 12,
    height: 12,
    marginRight: 3
  },
  colTitle: {
    fontWeight: 500,
    fontSize: 12,
    color: "#333333"
  },
  colText: {
    paddingHorizontal: 8,
    textAlign: "center",
    marginTop: 4,
    fontWeight: 500,
    fontSize: 12,
    lineHeight: 18,
    color: "#999999"
  },
  modeBox: {
    marginTop: 15,
    backgroundColor: "rgba(109,146,94,0.02)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(109,146,94,0.3)",
    padding: 15,
  },
  tipBox: {
    height: 17,
    backgroundColor: "#6D925E",
    borderRadius: 4,
    marginRight: 6,
    paddingHorizontal: 4,
  },
  tipBoxTitle: {
    fontWeight: "bold",
    fontSize: 12,
    color: "#FFFFFF",
  },
  tipBoxText: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#333333",
  },
  tipBoxText1: {
    marginTop: 4,
    fontWeight: 500,
    fontSize: 13,
    lineHeight: 18,
    color: "#666666",
  },
  tipBox1: {
    marginTop: 8,
    backgroundColor: 'rgba(109,146,94,0.1)',
    borderRadius: 8,
    padding: 12,
    alignItems: 'flex-start',
  },
  tipBox1Img: {
    width: 12,
    height: 12,
    marginRight: 4,
    marginTop: 3,
  },
  tipBox1Text: {
    flex: 1,
    flexShrink: 1,
    fontWeight: 500,
    fontSize: 12,
    lineHeight: 18,
    color: '#6D925E',
  },
  backImage1: {
    width: "100%",
    height: 50,
    marginTop: 12,
  },
  backImage1Text: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#333333",
  },
  nutritionContent: {
    marginHorizontal: 12,
    padding: 15,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 12,
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  tabBox: {
  },
  tabItem: {
    marginTop: 8,
    height: 19,
    marginRight: 6,
    borderRadius: 4,
    paddingHorizontal: 4,
    backgroundColor: "#FFF7DF",
    borderWidth: 1,
    borderColor: "#D2CFC0"
  },
  tabItemText: {
    fontWeight: 500,
    fontSize: 12,
    color: "#C98A41",
  },
  fxBox: {
    marginTop: 16,
  },
  fxIcon: {
    width: 15,
    height: 15,
  },
  fxTitle: {
    fontWeight: 500,
    fontSize: 15,
    color: "#333333",
    marginLeft: 4
  },
  fxBackBox: {
    marginTop: 16,
    minHeight: 126,
    borderRadius: 12,
    overflow: "hidden",
  },
  fxBackBoxContentImg: {
    marginTop: 8,
    marginRight: 5,
    width: 4,
    height: 4,
    backgroundColor: "#694F2B",
    borderRadius: 2,
    flexShrink: 0,
  },
  fxBackBoxContent: {
    minHeight: 126,
    paddingTop: 10,
    paddingBottom: 12,
    paddingLeft: 90,
    paddingRight: 12,
  },
  fxTextCol: {
    marginTop: 10,
    width: '100%',
  },
  fxText: {
    flex: 1,
    flexShrink: 1,
    fontWeight: 500,
    fontSize: 13,
    lineHeight: 20,
  },
  jcContent: {
    marginTop: 12,
    padding: 15,
    marginHorizontal: 12,
    borderRadius: 12,
    shadowColor: '#053A93',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  jcRightBox: {
    height: 21,
    paddingHorizontal: 8,
    backgroundColor: "rgba(114,161,197,0.12)",
    borderRadius: 25,
  },
  jcRightText: {
    fontWeight: 500,
    fontSize: 11,
    color: "#72A1C5"
  },
  jcTextWrap: {
    position: 'relative',
    marginTop: 16,
  },
  jcText: {
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 22,
    color: "#999999",
  },
  jcTextMeasure: {
    position: 'absolute',
    opacity: 0,
    left: 0,
    right: 0,
    zIndex: -1,
  },
  jcExpandBtn: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    height: 22,
    justifyContent: 'center',
  },
  jcExpandGradient: {
    height: 22,
    paddingLeft: 20,
    justifyContent: 'center',
  },
  jcExpandText: {
    fontWeight: 500,
    fontSize: 14,
    color: '#6D925E',
    marginRight: 2,
  },
  jcExpandIcon: {
    width: 11,
    height: 11,
    marginRight: 6,
  },
  mealBottomBar: {
    position: 'absolute',
    alignSelf: 'center',
    left: 12,
    right: 12,
    height: 51,
    backgroundColor: '#FFFFFF',
    borderRadius: 29,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 15,
    elevation: 3,
    paddingHorizontal: 14,
    alignItems: 'center',
    zIndex: 2,
  },
  bottomInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  mealMicWrap: {
    width: 28,
    height: 28,
    marginRight: 8,
    overflow: 'visible',
  },
  mealInputIcon: {
    width: 20,
    height: 20,
    marginRight: 16,
  },
  mealInput: {
    flex: 1,
    height: 36,
    paddingHorizontal: 0,
    fontSize: 15,
    color: '#333333',
  },
  mealBtmIconBox: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  mealBtmIcon: {
    width: 30,
    height: 30,
  },
})

export default styles
