import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    page: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { flex: 1, paddingHorizontal: 12, paddingTop: 12, },
    scrollContent: { paddingBottom: 120 },
    commonWrap: {
        marginTop: 12,
        paddingHorizontal: 15,
        paddingVertical: 13,
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        alignItems: 'center',
        shadowColor: '#B4C9FF', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.14, shadowRadius: 4, elevation: 3
    },
    medicationBox: {
        marginTop: 18,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        backgroundColor: "#FFFFFF",
        borderRadius: 18,
        paddingHorizontal: 24,
        paddingVertical: 18,
    },
    btmLine: {
        marginTop: 4,
        height: 1,
        backgroundColor: "rgba(23,63,125,0.08)"
    },
    inputBox: {
        marginTop: 21,
    },
    fieldLabel: {
        fontWeight: '400',
        fontSize: 16,
        color: '#333333',
    },
    nameInput: {
        marginTop: 12,
        width: '100%',
        height: 39,
        backgroundColor: '#F3F5F9',
        borderRadius: 25,
        paddingHorizontal: 16,
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        paddingVertical: 0,
    },
    servingTitleWrap: {
        marginTop: 0,
        marginBottom: 12,
    },
    servingRow: {
        marginTop: 20,
        width: '100%',
        gap: 12,
    },
    servingCol: {
        flex: 1,
        flexBasis: 0,
        minWidth: 0,
    },
    servingAmountInput: {
        width: '100%',
        height: 39,
        backgroundColor: '#F3F5F9',
        borderRadius: 25,
        paddingHorizontal: 16,
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        paddingVertical: 0,
    },
    servingUnitBtn: {
        width: '100%',
        height: 39,
        paddingHorizontal: 16,
        backgroundColor: '#F3F5F9',
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
    },
    servingUnitText: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    mealPeriodSection: {
        marginTop: 20,
        width: '100%',
    },
    mealPeriodRow: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    mealPeriodChip: {
        flex: 1,
        height: 70,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E5E5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mealPeriodChipActive: {
        backgroundColor: 'rgba(109,146,94,0.1)',
        borderColor: '#6D925E',
    },
    mealPeriodIcon: {
        width: 24,
        height: 24,
    },
    mealPeriodText: {
        marginTop: 4,
        fontWeight: '500',
        fontSize: 13,
        color: '#000000',
    },
    mainTitle: {
        fontWeight: 500,
        fontSize: 16,
        color: "#333333",
        marginBottom: 6,
    },
    mainRowWrap: {
        width: '100%',
    },
    mainContent: {
        width: '100%',
        height: 60,
    },
    mainDivider: {
        width: '100%',
        height: 1,
        backgroundColor: 'rgba(23,63,125,0.08)',
    },
    mainDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 8,
    },
    maiinIconText: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    mainValue: { fontWeight: 500, fontSize: 16, color: '#173F7D' },
    mainValueInput: {
        width: 50,
        textAlign: 'right',
        fontWeight: 'bold',
        fontSize: 18,
        color: '#333333',
        paddingVertical: 0,
    },
    mainUnit: {
        width: 35,
        textAlign: 'right',
        fontWeight: 'bold',
        fontSize: 14,
        color: '#999999',
    },
    delIcon: { width: 28, height: 28, marginLeft: 40 },
    addText: { fontWeight: 500, fontSize: 12, color: '#173F7D' },
    addButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        marginRight: -14,
        marginVertical: -10,
    },
    addItemBtn: {
        marginTop: 12,
        width: '100%',
        height: 48,
        backgroundColor: '#F6F8FB',
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addItemIcon: {
        width: 16,
        height: 16,
        marginRight: 6,
    },
    addItemText: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    noteText: { fontWeight: 500, fontSize: 13, color: '#999999', marginTop: 12 },
    bottomBar: {
        paddingHorizontal: 15,
        paddingTop: 15,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 12,
    },
    primaryBtn: {
        marginTop: 4,
        height: 50,
        borderRadius: 12,
        backgroundColor: AppTheme.primaryColor,
        justifyContent: 'center',
        alignItems: 'center',
    },
    primaryBtnIcon: {
        width: 20,
        height: 20,
        marginRight: 4,
    },
    primaryBtnText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    customNameInput: {
        flex: 1,
        marginRight: 12,
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
        paddingVertical: 0,
    },
    errorText: {
        marginTop: 4,
        fontSize: 12,
        color: '#FF4D4F',
    },

    sectionTitleWrap: { marginLeft: 4, position: 'relative', alignSelf: 'flex-start' },
    sectionTitleText: { marginLeft: 0, fontSize: 16, color: "#333333", fontWeight: "bold" },
    sectionTitleUnderline: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: 7,
        borderRadius: 25,
    },
    pageTopBgText: { fontWeight: "bold", fontSize: 12, color: "#333333", marginLeft: 4 },

});

export default styles;
