import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  pageContent: { flex: 1, position: 'relative' },
  body: { padding: 12, paddingTop: 2, paddingBottom: 110 },
  emptyWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  resultCard: {
    backgroundColor: '#FEFFFF',
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
  },
  resultTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
    alignSelf: 'flex-start',
  },
  resultGaugeOuter: {
    marginTop: 14,
    width: 125,
    height: 125,
    borderRadius: 125,
    backgroundColor: '#F8F9FE',
    borderWidth: 1,
    borderColor: '#EAECF8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultGaugeInner: {
    width: 106,
    height: 106,
    borderRadius: 100,
    backgroundColor: '#F8F9FE',
    borderWidth: 1,
    borderColor: '#EAECF8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultGauge: {
    width: 80,
    height: 80,
  },
  resultLevel: {
    marginTop: 12,
    fontWeight: 'bold',
    fontSize: 15,
    color: '#333333',
    textAlign: 'center',
  },
  resultTime: {
    marginTop: 6,
    fontWeight: '500',
    fontSize: 12,
    color: '#999999',
    textAlign: 'center',
  },
  resultDivider: {
    marginTop: 15,
    alignSelf: 'stretch',
    height: 1,
    backgroundColor: '#E7EAEB',
  },
  resultStatsRow: {
    marginTop: 25,
    marginBottom: 10,
    alignSelf: 'stretch',
  },
  resultStatItem: {
    flex: 1,
    alignItems: 'center',
  },
  resultStatValue: {
    fontWeight: 'bold',
    fontSize: 22,
    color: '#333333',
  },
  resultStatLabel: {
    marginTop: 8,
    fontWeight: '400',
    fontSize: 13,
    color: '#999999',
  },
  resultTipBox: {
    marginTop: 15,
    alignSelf: 'stretch',
    padding: 12,
    backgroundColor: '#F6F7FA',
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  resultTipIcon: {
    width: 15,
    height: 15,
    marginTop: 3,
    marginRight: 8,
  },
  resultTipText: {
    flex: 1,
    fontWeight: '500',
    fontSize: 14,
    color: '#333333',
    lineHeight: 21,
  },
  resultDisclaimer: {
    marginTop: 12,
    padding: 12,
    backgroundColor: 'rgba(254,248,225,0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(238,156,68,0.3)',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  resultDisclaimerIcon: {
    width: 15,
    height: 15,
    marginTop: 2,
    marginRight: 8,
  },
  resultDisclaimerText: {
    flex: 1,
    fontWeight: '500',
    fontSize: 13,
    color: '#C98A41',
    lineHeight: 20,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    paddingHorizontal: 15,
    paddingTop: 12,
    backgroundColor: '#FEFEFE',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    shadowColor: '#B4C9FF',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.14,
    shadowRadius: 4,
    elevation: 8,
  },
  bottomBarButtonCancel: {
    flex: 1,
    height: 50,
    marginRight: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  bottomBarButtonConfirm: {
    flex: 1,
    height: 50,
    backgroundColor: '#6D925E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  bottomBarButtonTextCancel: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#6D925E',
  },
  bottomBarButtonTextConfirm: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  answerCard: {
    marginTop: 12,
    backgroundColor: '#FEFFFF',
    borderRadius: 12,
    padding: 15,
  },
  answerCardTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333333',
  },
  answerQuestion: {
    marginTop: 14,
  },
  answerQuestionBar: {
    marginTop: 5,
    width: 4,
    height: 11,
    backgroundColor: '#6D925E',
    borderRadius: 25,
    marginRight: 6,
  },
  answerQuestionTitle: {
    flex: 1,
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 22,
    color: '#333333',
  },
  answerSelectedBox: {
    marginTop: 15,
    backgroundColor: '#F6F7FA',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  answerSelectedText: {
    fontWeight: '500',
    fontSize: 14,
    color: '#333333',
    textAlign: 'center',
  },
});

export default styles;
