import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { padding: 18, paddingTop: 2, paddingBottom: 40 },
    calendarBox: {
        marginTop: 12,
        padding: 15,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 2,
    },
    calendarHeader: {
        marginBottom: 8,
    },
    calendarTodayBtn: {
        minWidth: 40,
    },
    calendarTodayText: {
        fontWeight: 'bold',
        fontSize: 12,
        color: '#EE9C44',
    },
    calendarMonthNav: {
        flex: 1,
        justifyContent: 'center',
    },
    calendarMonthText: {
        width: 132,
        height: 19,
        fontWeight: 'bold',
        fontSize: 15,
        lineHeight: 19,
        color: '#333333',
        textAlign: 'center',
    },
    calendarArrow: {
        width: 6,
        height: 10,
    },
    calendarArrowBtn: {
        width: 32,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
    },
    calendarWeekRow: {
        marginTop: 13,
        height: 64,
    },
    calendarCol: { width: 38, height: '100%', borderRadius: 25, backgroundColor: 'transparent' },
    calendarColActive: { backgroundColor: 'rgba(109,146,94,0.12)' },
    calendarTitle: {
        fontWeight: 'bold',
        fontSize: 13,
        color: '#666666',
        marginTop: 12,
        textAlign: 'center',
    },
    calendarTitleActive: {
        fontWeight: 'bold',
        fontSize: 13,
        color: AppTheme.primaryColor,
        marginTop: 12,
        textAlign: 'center',
    },
    calendarSubtitle: {
        fontWeight: '500',
        fontSize: 18,
        marginTop: 5,
        color: AppTheme.textPrimary,
        textAlign: 'center',
    },
    calendarSubtitleActive: {
        fontWeight: '500',
        fontSize: 18,
        marginTop: 5,
        color: AppTheme.primaryColor,
        textAlign: 'center',
    },
    mapBox: {
        padding: 15,
        borderRadius: 12,
        marginTop: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1
    },
    mapIcon: { width: 24, height: 24 },
    mapTime: { fontWeight: 'bold', fontSize: 18, color: '#333333' },
    goalTitle: { marginLeft: 7 },
    goalStatusBadge: {
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        paddingHorizontal: 6,
        height: 22,
        justifyContent: 'center',
        alignItems: 'center',
    },
    goalStatusText: {
        fontWeight: 'bold',
        fontSize: 11,
    },
    goalBody: {
        marginTop: 16,
        alignItems: 'flex-start',
    },
    stepsBody: {
        marginTop: 16,
    },
    stepsMetricLabel: {
        fontWeight: "bold",
        fontSize: 16,
        color: '#333333',
    },
    stepsMetricValue: {
        fontWeight: 'bold',
        fontSize: 22,
        color: '#333333',
    },
    stepsMetricUnit: {
        marginLeft: 6,
        fontWeight: '500',
        fontSize: 14,
        color: '#999999',
    },
    stepsGoalRow: {
        marginTop: 12,
    },
    goalLeft: {
        flexShrink: 0,
        minWidth: 121,
        marginRight: 16,
    },
    goalMetricLabel: {
        marginTop: 8,
        textAlign: "center",
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    goalMetricValue: {
        marginTop: 8,
        textAlign: "center",
        fontWeight: 'bold',
        fontSize: 22,
        color: '#333333',
    },
    goalMetricUnit: {
        marginTop: 8,
        textAlign: "center",
        fontWeight: '500',
        fontSize: 14,
        color: '#999999',
    },
    goalRight: {
        flex: 1,
        minWidth: 0,
    },
    goalRowSpaced: {
        marginTop: 21,
    },
    goalRowLabel: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    goalRowValue: {
        fontWeight: '500',
        fontSize: 14,
        color: '#999999',
    },
    goalRowTrack: {
        marginTop: 8,
        height: 6,
        borderRadius: 3,
        backgroundColor: 'rgba(153,153,153,0.15)',
        overflow: 'hidden',
    },
    goalRowFill: {
        height: '100%',
        borderRadius: 3,
    },
    mapValueBox: { height: 24, paddingHorizontal: 18, backgroundColor: 'rgba(237,194,98,0.14)', borderRadius: 12 },
    mapValue: { fontWeight: '500', fontSize: 12, color: '#FFBA1D' },
    mapItemMain: { marginTop: 19, marginBottom: 1 },
    mapItemLeftText: { fontWeight: '500', fontSize: 24, color: AppTheme.textPrimary },
    mapItemLeftUnit: { fontWeight: '400', fontSize: 12, color: AppTheme.textSecondary },
    sleepStageSection: { paddingLeft: 18, paddingRight: 8, marginTop: 4 },
    sleepStageRow: { marginTop: 6, alignItems: 'center' },
    sleepStageLabel: { width: 56, fontWeight: '400', fontSize: 12, color: AppTheme.textSecondary },
    sleepStageTrack: {
        flex: 1,
        height: 8,
        borderRadius: 3,
        marginHorizontal: 8,
        overflow: 'hidden',
    },
    sleepStageFill: { height: '100%', borderRadius: 3 },
    sleepStageDuration: {
        width: 80,
        fontWeight: '400',
        fontSize: 12,
        color: AppTheme.textSecondary,
        textAlign: 'right',
    },
    mapItemLeft: { flex: 1, flexShrink: 1, paddingRight: 12 },
    mapItemRight: { flexShrink: 0, alignItems: 'baseline' },
    mapItemText: { fontWeight: '500', fontSize: 15, color: '#333333' },
    mapItemValue: { fontWeight: 'bold', fontSize: 22, color: '#333333', textAlign: 'left' },
    mapItemBz: { marginTop: 8, fontWeight: '500', fontSize: 12, color: AppTheme.textSecondary, lineHeight: 18 },
    mapItemUnit: { marginLeft: 6, fontWeight: '500', fontSize: 14, color: '#999999' },
    lipidMetricRow: { marginTop: 10 },
    lipidMetricLabel: { fontWeight: '400', fontSize: 14, color: AppTheme.textSecondary },
    lipidMetricValue: { fontWeight: '500', fontSize: 16, color: AppTheme.textPrimary },
    lipidMetricUnit: { marginLeft: 4, fontWeight: '400', fontSize: 12, color: AppTheme.textSecondary },
    lipidMetricStatus: { marginLeft: 8, fontWeight: '500', fontSize: 12 },
    rowLine: { height: 1, backgroundColor: '#E8DED2' },
    mapLeftText: {
        marginTop: 12,
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    mapRightText: {
        marginTop: 12,
        fontWeight: '500',
        fontSize: 14,
        textAlign: 'right',
        color: '#333333',
    },
    remarkBox: { marginTop: 4, paddingHorizontal: 18 },
    remarkFullText: { marginTop: 8, fontWeight: '400', fontSize: 14, lineHeight: 20, color: AppTheme.textPrimary },
    expandBtn: { marginTop: 12, alignItems: 'center', justifyContent: 'center' },
    expandBtnExpanded: { marginBottom: 12 },
    expandIcon: { width: 39, height: 18 },
    expandDetail: { paddingVertical: 5 },
    swipeRow: {
        marginTop: 16,
        borderRadius: 8,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        elevation: 3,
    },
    swipeAction: { position: 'absolute', top: 0, right: 0, bottom: 0, width: 72, zIndex: 0 },
    swipeForeground: { width: '100%', zIndex: 1, backgroundColor: '#FFFFFF', borderRadius: 8 },
    swipeDeleteBtn: { flex: 1, width: 72, justifyContent: 'center', alignItems: 'center' },
    swipeDeleteIcon: { width: 24, height: 24 },
    mapBoxInSwipe: {
        marginTop: 0,
        shadowColor: 'transparent',
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
    },
    loadingBox: { marginTop: 24, alignItems: 'center' },
    emptyBox: { marginTop: 24, alignItems: 'center' },
    emptyText: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
});

export default styles;
