import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
    body: { padding: 18, paddingTop: 2, paddingBottom: 40 },
    rowBox: {
        padding: 22,
        borderRadius: 8,
        marginTop: 16,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1
    },
    dayTitleBtn: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    dayTitle: { fontWeight: 400, fontSize: 16, color: AppTheme.textPrimary, textAlign: 'center' },
    navIcon: { width: 24, height: 24 },
    navIconRight: { width: 24, height: 24, transform: [{ rotate: '180deg' }] },
    weekHead: { flexDirection: 'row', marginTop: 20 },
    weekCell: { flex: 1, height: 21, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 21, textAlign: 'center' },
    divider: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12, marginBottom: 8, overflow: 'hidden' },
    dash: { width: 5, height: 1, backgroundColor: 'rgba(153,153,153,0.17)' },
    calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
    dayCell: { width: '14.28%', height: 36, justifyContent: 'center', alignItems: 'center' },
    dayText: { fontWeight: 400, fontSize: 14, color: AppTheme.textPrimary, lineHeight: 21, textAlign: 'center' },
    dayTextOther: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary, lineHeight: 21, textAlign: 'center' },
    dayInner: { width: 24, height: 24, justifyContent: 'center', alignItems: 'center' },
    daySelected: { backgroundColor: '#053A93', borderRadius: 20 },
    dayTextSelected: { fontWeight: 400, fontSize: 14, color: '#FFFFFF', textAlign: 'center' },
    mapBox: {
        paddingHorizontal: 10,
        paddingBottom: 14,
        borderRadius: 8,
        marginTop: 16,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1
    },
    mapIcon: { width: 24, height: 24 },
    mapTime: { marginLeft: 7, fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary },
    mapValueBox: { height: 24, paddingHorizontal: 18, backgroundColor: "rgba(237,194,98,0.14)", borderRadius: 12 },
    mapValue: { fontWeight: 500, fontSize: 12, color: "#FFBA1D" },
    mapItem: { marginTop: 15, marginBottom: 1, paddingLeft: 18, paddingRight: 8 },
    mapItemLeftText: { fontWeight: 500, fontSize: 24, color: AppTheme.textPrimary },
    mapItemLeftUnit: { fontWeight: 400, fontSize: 12, color: AppTheme.textSecondary },
    sleepStageSection: { paddingLeft: 18, paddingRight: 8, marginTop: 4 },
    sleepStageRow: { marginTop: 6, alignItems: 'center' },
    sleepStageLabel: { width: 56, fontWeight: 400, fontSize: 12, color: AppTheme.textSecondary },
    sleepStageTrack: {
        flex: 1,
        height: 8,
        borderRadius: 3,
        // backgroundColor: 'rgba(153,153,153,0.15)',
        marginHorizontal: 8,
        overflow: 'hidden',
    },
    sleepStageFill: { height: '100%', borderRadius: 3 },
    sleepStageDuration: {
        width: 80,
        fontWeight: 400,
        fontSize: 12,
        color: AppTheme.textSecondary,
        textAlign: 'right',
    },
    mapItemLeft: { flex: 1, flexShrink: 1, paddingRight: 12 },
    mapItemRight: { flexShrink: 0, alignItems: 'flex-start' },
    mapItemText: { fontWeight: 500, fontSize: 18, color: AppTheme.textPrimary },
    mapItemValue: { fontWeight: 500, fontSize: 20, color: AppTheme.textPrimary, textAlign: 'left' },
    mapItemBz: { marginTop: 8, fontWeight: 500, fontSize: 12, color: AppTheme.textSecondary, lineHeight: 18 },
    mapItemUnit: { marginTop: 8, fontWeight: 400, fontSize: 12, color: AppTheme.textSecondary, textAlign: 'left' },
    lipidMetricRow: { marginTop: 10 },
    lipidMetricLabel: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    lipidMetricValue: { fontWeight: 500, fontSize: 16, color: AppTheme.textPrimary },
    lipidMetricUnit: { marginLeft: 4, fontWeight: 400, fontSize: 12, color: AppTheme.textSecondary },
    lipidMetricStatus: { marginLeft: 8, fontWeight: 500, fontSize: 12 },
    rowLine: { height: 1, backgroundColor: '#E8DED2' },
    mapLeftText: {
        marginTop:12,
        fontWeight: 400,
        fontSize: 14,
        color: AppTheme.textSecondary,
    },
    mapRightText: { marginTop: 12, fontWeight: 400, fontSize: 14, textAlign: 'right', color: AppTheme.textPrimary },
    remarkBox: { marginTop: 4, paddingHorizontal: 18 },
    remarkFullText: { marginTop: 8, fontWeight: 400, fontSize: 14, lineHeight: 20, color: AppTheme.textPrimary },
    expandBtn: { marginTop: 12, alignItems: 'center', justifyContent: 'center' },
    expandBtnExpanded: { marginBottom: 12 },
    expandText: { marginRight: 2, fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
    expandDetail: { paddingBottom: 12 },
    swipeRow: {
        marginTop: 16,
        borderRadius: 8,
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        elevation: 3,
    },
    swipeAction: { position: 'absolute', top: 0, right: 0, bottom: 0, width: 72, zIndex: 0 },
    swipeForeground: { width: '100%', zIndex: 1, backgroundColor: '#FFFFFF', borderRadius: 8 },
    swipeDeleteBtn: { flex: 1, width: 72, justifyContent: 'center', alignItems: 'center' },
    swipeDeleteIcon: { width: 24, height: 24 },
    mapBoxInSwipe: {
        marginTop: 0,
        shadowColor: 'transparent',
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
    },
    loadingBox: { marginTop: 24, alignItems: 'center' },
    emptyBox: { marginTop: 24, alignItems: 'center' },
    emptyText: { fontWeight: 400, fontSize: 14, color: AppTheme.textSecondary },
});

export default styles;
