import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F7F7F9" },
    pageContent: { flex: 1, position: 'relative' },
    body: { paddingHorizontal: 12, paddingTop: 18, paddingBottom: 14, borderTopWidth: 1, borderColor: '#E9E9E9' },
    typeListFade: { position: 'absolute', top: 0, left: 0, right: 0, height: 66, borderRadius: 0, zIndex: -1 },
    typeListBox: { height: 30, backgroundColor: '#EDEEEF', borderRadius: 25, padding: 2, zIndex: 2 },
    typeItem: { flex: 1 },
    typeItemActive: { flex: 1, height: "100%", backgroundColor: '#FFFFFF', borderRadius: 25 },
    typeItemText: { fontWeight: 500, fontSize: 12, color: '#333333' },
    rowBox: { marginTop: 18, padding: 15, borderRadius: 12, backgroundColor: '#FFFFFF', shadowColor: AppTheme.primaryColor, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, overflow: 'visible' },
    rowBoxList: { marginTop: 18, gap: 12 },
    rowTitle: { fontWeight: 500, fontSize: 12, color: '#666666' },
    rowLeftValue: { marginTop: 6, fontWeight: "bold", fontSize: 25, marginBottom: 8, color: '#333333' },
    rowValueBox: { marginTop: 3 },
    rowValueText: { fontWeight: 'bold', fontSize: 14, color: '#333333' },
    rowValueNum: { fontWeight: 'bold', fontSize: 24, color: '#6D925E', marginHorizontal: 3 },
    progressRing: { width: 50, height: 50, justifyContent: 'center', alignItems: 'center', overflow: 'visible' },
    progressCanvas: { width: 50, height: 50, position: 'absolute' },
    progressText: { fontWeight: 'bold', fontSize: 14, color: '#333333' },
    statusBox: { backgroundColor: '#FFFFFF', borderRadius: 4, borderWidth: 1, paddingHorizontal: 6, paddingVertical: 4, borderColor: '#6D925E' },
    statusText: { fontWeight: "bold", fontSize: 11, color: "#6D925E" },
    status1Box: { backgroundColor: '#FFFFFF', borderRadius: 4, borderWidth: 1, paddingHorizontal: 6, paddingVertical: 4, borderColor: '#EE9C44' },
    status1Text: { fontWeight: "bold", fontSize: 11, color: "#EE9C44" },
    dayBox: { padding: 6, backgroundColor: 'rgba(109,146,94,0.14)', borderRadius: 4 },
    dayText: { fontWeight: 500, fontSize: 12, color: "#6D925E" },
    chartBox: { marginTop: 12, position: 'relative', overflow: 'visible' },
    chartXLabel: { position: 'absolute', fontSize: 10, color: '#999999', lineHeight: 14 },
    chartSelectionTip: { position: 'absolute', minWidth: 56, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, backgroundColor: 'rgba(51,51,51,0.9)', zIndex: 25 },
    chartSelectionTipTitle: { fontSize: 10, color: '#FFFFFF', lineHeight: 14 },
    chartSelectionTipValue: { fontSize: 10, color: '#FFFFFF', lineHeight: 14, fontWeight: 'bold' },
    chartSliderTrack: { position: 'absolute', left: 0, zIndex: 20 },
    chartSliderThumb: { position: 'absolute' },
    colTopBox: { marginTop: 36, gap: 35 },
    colLeftBor: { width: 9, height: 9, backgroundColor: '#EE9C44', borderRadius: 5 },
    colLeftText: { fontWeight: "bold", fontSize: 12, color: "#EE9C44", marginLeft: 3 },
    colRightBor: { width: 9, height: 9, backgroundColor: '#0951AE', borderRadius: 5 },
    colRightText: { fontWeight: "bold", fontSize: 12, color: "#0951AE", marginLeft: 3 },
    colRow: { marginTop: 12, gap: 10 },
    colBox: {
        flex: 1,
        paddingHorizontal: 10,
        paddingVertical: 15,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        overflow: 'visible',
        position: "relative"
    },
    rValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#333333" },
    eValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#FB4550" },
    analysisTitle: { fontWeight: "bold", fontSize: 16, color: "#333333" },
    analysisBox: { marginTop: 3 },
    analysisItem: { marginTop: 12 },
    analysisBor: { width: 10, height: 10, backgroundColor: '#6D925E', borderRadius: 5 },
    analysisText: { marginLeft: 8, width: 80, fontWeight: 500, fontSize: 14, color: "#333" },
    analysisValue: { fontWeight: "bold", fontSize: 14, marginLeft: 13, color: "#333333" },
    analysisValueEmpty: { fontWeight: "bold", fontSize: 14, marginLeft: 13, color: "#999999" },
    bottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 18,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 12,
        borderTopRightRadius: 12,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    bottomBarButtonLeft: {
        height: 50,
        backgroundColor: '#6D925E',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#6D925E',
    },
    bottomBarButtonImg: {
        width: 20,
        height: 20,
        marginRight: 4,
    },
    bottomBarButtonTextLeft: {
        fontWeight: 'bold',
        fontSize: 18,
        color: '#FFFFFF',
    },
    HValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#EE9C44" },
    LValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#0951AE" },
    colLBor: { width: 9, height: 9, backgroundColor: '#6D925E', borderRadius: 5 },
    colLText: { fontWeight: "bold", fontSize: 12, color: "#6D925E", marginLeft: 3 },
    colHBor: { width: 9, height: 9, backgroundColor: '#EE9C44', borderRadius: 5 },
    colHText: { fontWeight: "bold", fontSize: 12, color: "#EE9C44", marginLeft: 3 },
    rowIntro: { fontWeight: 500, fontSize: 11, color: '#999999', marginTop: 8 },
    colImage1: { width: 79, height: 30, position: 'absolute', right: 6, bottom: 6 },
    colImage2: { width: 73, height: 32, position: 'absolute', right: 6, bottom: 6 },
    colImage3: { width: 70, height: 38, position: 'absolute', right: 6, bottom: 6 },
    analysis1: { fontWeight: 500, textAlign: "center", fontSize: 12, color: "#666666" },
    analysis2: { fontWeight: "bold", textAlign: "center", fontSize: 25, color: "#333333", marginTop: 8 },
    analysisContent: { marginTop: 15, paddingHorizontal: 18 },
    analysis3: { fontWeight: "bold", textAlign: "center", fontSize: 25, color: "#EE9C44", marginTop: 8 },
    analysisIntro: { marginTop: 12, borderRadius: 8, backgroundColor:"#F6F8FB",paddingVertical:10 },
    analysisIntroText: { fontWeight: 500, fontSize: 12, color: '#666666'},
})

export default styles
