import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F7F7F9" },
    pageContent: { flex: 1, position: 'relative' },
    body: { paddingHorizontal: 12, paddingTop: 12, paddingBottom: 14 },
    pageHeader: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 6, borderTopWidth: 1, borderColor: '#E9E9E9' },
    typeListFade: { position: 'absolute', top: 0, left: 0, right: 0, height: 66, borderRadius: 0, zIndex: -1 },
    typeListBox: { height: 30, backgroundColor: '#EDEEEF', borderRadius: 25, padding: 2, zIndex: 2 },
    typeItem: { flex: 1 },
    typeItemActive: { flex: 1, height: "100%", backgroundColor: '#FFFFFF', borderRadius: 25 },
    typeItemText: { fontWeight: 500, fontSize: 12, color: '#333333' },
    rowBox: { marginTop: 18, padding: 15, borderRadius: 12, backgroundColor: '#FFFFFF', shadowColor: AppTheme.primaryColor, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, overflow: 'visible' },
    rowBoxList: { marginTop: 18, gap: 12 },
    rowTitle: { fontWeight: 500, fontSize: 12, color: '#666666' },
    rowLeftValue: { marginTop: 6, fontWeight: "bold", fontSize: 25, marginBottom: 8, color: '#333333' },
    rowValueBox: { marginTop: 3 },
    rowValueText: { fontWeight: 'bold', fontSize: 14, color: '#333333' },
    rowValueNum: { fontWeight: 'bold', fontSize: 24, color: '#6D925E', marginHorizontal: 3 },
    progressRing: { width: 50, height: 50, justifyContent: 'center', alignItems: 'center', overflow: 'visible' },
    progressCanvas: { width: 50, height: 50, position: 'absolute' },
    progressText: { fontWeight: 'bold', fontSize: 14, color: '#333333' },
    statusBox: { backgroundColor: '#FFFFFF', borderRadius: 4, borderWidth: 1, paddingHorizontal: 6, paddingVertical: 4, borderColor: '#6D925E' },
    statusText: { fontWeight: "bold", fontSize: 11, color: "#6D925E" },
    todayMetricLabel: { fontWeight: '500', fontSize: 12, color: '#666666' },
    todayMetricValue: { marginTop: 8, fontWeight: 'bold', fontSize: 25, color: '#333333' },
    todayMetricRight: { alignItems: 'flex-end' },
    todayProgressTrack: {
        marginTop: 12,
        height: 12,
        backgroundColor: '#ECEDF1',
        borderRadius: 25,
        overflow: 'hidden',
    },
    todayProgressFill: {
        height: '100%',
        backgroundColor: '#EE9C44',
        borderRadius: 25,
    },
    todayRemainRow: {
        marginTop: 12,
        alignItems: 'center',
    },
    todayRemainAccent: {
        width: 3,
        height: 12,
        backgroundColor: '#EE9C44',
        borderRadius: 25,
        marginRight: 8,
    },
    todayRemainText: {
        fontWeight: '500',
        fontSize: 14,
        color: '#333333',
    },
    todayRemainNum: {
        fontWeight: 'bold',
        fontSize: 15,
        color: '#333333',
    },
    status1Box: { backgroundColor: '#FFFFFF', borderRadius: 4, borderWidth: 1, paddingHorizontal: 6, paddingVertical: 4, borderColor: '#EE9C44' },
    status1Text: { fontWeight: "bold", fontSize: 11, color: "#EE9C44" },
    dayBox: { padding: 6, backgroundColor: 'rgba(109,146,94,0.14)', borderRadius: 4 },
    dayText: { fontWeight: 500, fontSize: 12, color: "#6D925E" },
    chartBox: { marginTop: 12, position: 'relative', overflow: 'visible' },
    chartXLabel: { position: 'absolute', fontSize: 10, color: '#999999', lineHeight: 14 },
    chartSelectionTip: { position: 'absolute', minWidth: 56, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, backgroundColor: 'rgba(51,51,51,0.9)', zIndex: 25 },
    chartSelectionTipTitle: { fontSize: 10, color: '#FFFFFF', lineHeight: 14 },
    chartSelectionTipValue: { fontSize: 10, color: '#FFFFFF', lineHeight: 14, fontWeight: 'bold' },
    chartSafetyLineLabel: { position: 'absolute', fontSize: 12, fontWeight: 'bold', color: '#EE9C44', lineHeight: 16, zIndex: 25 },
    chartSliderTrack: { position: 'absolute', left: 0, zIndex: 20 },
    chartSliderThumb: { position: 'absolute' },
    colTopBox: { marginTop: 36, gap: 35 },
    colLeftBor: { width: 9, height: 9, backgroundColor: '#EE9C44', borderRadius: 5 },
    colLeftText: { fontWeight: "bold", fontSize: 12, color: "#EE9C44", marginLeft: 3 },
    colRightBor: { width: 9, height: 9, backgroundColor: '#72A1C5', borderRadius: 5 },
    colRightText: { fontWeight: "bold", fontSize: 12, color: "#72A1C5", marginLeft: 3 },
    colRow: { marginTop: 12, gap: 10 },
    colBox: {
        flex: 1,
        paddingHorizontal: 10,
        paddingVertical: 15,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
        shadowColor: AppTheme.primaryColor,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        overflow: 'visible',
        position: "relative"
    },
    rValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#333333" },
    eValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#FB4550" },
    analysisTitle: { fontWeight: "bold", fontSize: 16, color: "#333333" },
    analysisBox: { marginTop: 3 },
    analysisItem: { marginTop: 12 },
    analysisBor: { width: 10, height: 10, backgroundColor: '#6D925E', borderRadius: 5 },
    analysisText: { marginLeft: 8, width: 80, fontWeight: 500, fontSize: 14, color: "#333" },
    analysisValue: { fontWeight: "bold", fontSize: 14, marginLeft: 13, color: "#333333" },
    analysisValueEmpty: { fontWeight: "bold", fontSize: 14, marginLeft: 13, color: "#999999" },
    bottomBar: {
        width: '100%',
        paddingHorizontal: 15,
        paddingTop: 15,
        paddingBottom: 40,
        backgroundColor: '#FEFEFE',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: '#B4C9FF',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.14,
        shadowRadius: 4,
        elevation: 3,
    },
    bottomBarButtonLeft: {
        marginTop: 4,
        height: 50,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottomBarButtonImg: {
        width: 20,
        height: 20,
        marginRight: 4,
    },
    bottomBarButtonTextLeft: {
        fontWeight: '600',
        fontSize: 16,
        color: '#FFFFFF',
    },
    HValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#EE9C44" },
    LValue: { marginTop: 8, fontWeight: "bold", fontSize: 25, color: "#72A1C5" },
    colLBor: { width: 9, height: 9, backgroundColor: '#6D925E', borderRadius: 5 },
    colLText: { fontWeight: "bold", fontSize: 12, color: "#6D925E", marginLeft: 3 },
    colHxBor: { width: 9, height: 9, backgroundColor: '#FB4550', borderRadius: 5 },
    colHxText: { fontWeight: "bold", fontSize: 12, color: "#FB4550", marginLeft: 3 },
    colHBor: { width: 9, height: 9, backgroundColor: '#EE9C44', borderRadius: 5 },
    colHText: { fontWeight: "bold", fontSize: 12, color: "#EE9C44", marginLeft: 3 },
    rowIntro: { fontWeight: 500, fontSize: 11, color: '#999999', marginTop: 8 },
    colImage1: { width: 79, height: 30, position: 'absolute', right: 6, bottom: 6 },
    colImage2: { width: 73, height: 32, position: 'absolute', right: 6, bottom: 6 },
    colImage3: { width: 70, height: 38, position: 'absolute', right: 6, bottom: 6 },
    analysis1: { fontWeight: 500, textAlign: "center", fontSize: 12, color: "#666666" },
    analysis2: { fontWeight: "bold", textAlign: "center", fontSize: 25, color: "#333333", marginTop: 8 },
    analysisContent: { marginTop: 15, paddingHorizontal: 18 },
    analysis3: { fontWeight: "bold", textAlign: "center", fontSize: 25, color: "#EE9C44", marginTop: 8 },
    analysisIntro: { marginTop: 12, borderRadius: 8, backgroundColor: "#F6F8FB", paddingVertical: 10 },
    analysisIntroText: { fontWeight: 500, fontSize: 12, color: '#666666' },
    bmiProgressWrap: { marginTop: 16, width: '100%' },
    bmiProgressTrack: { position: 'relative', paddingTop: 16 },
    bmiProgressBar: {
        flexDirection: 'row',
        height: 10,
        gap: 3,
    },
    bmiProgressSegment: {
        flex: 1,
    },
    bmiProgressSegmentFirst: {
        borderTopLeftRadius: 4,
        borderBottomLeftRadius: 4,
    },
    bmiProgressSegmentLast: {
        borderTopRightRadius: 4,
        borderBottomRightRadius: 4,
    },
    bmiProgressMarkerWrap: {
        position: 'absolute',
        top: 0,
        alignItems: 'center',
        zIndex: 2,
    },
    bmiProgressMarkerIcon: {
        width: 12,
        height: 12,
    },
    bmiProgressLabels: { marginTop: 10 },
    bmiProgressLabelItem: {
        flex: 1,
        alignItems: 'center',
    },
    bmiProgressLabel: {
        fontWeight: '500',
        fontSize: 13,
        color: '#333333',
        textAlign: 'center',
    },
    bmiProgressRangeLabel: {
        marginTop: 6,
        fontWeight: '500',
        fontSize: 12,
        color: '#999999',
        textAlign: 'center',
    },
    todayBmiTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#333333',
    },
    todayOverviewLabel: {
        marginTop: 15,
        fontWeight: '500',
        fontSize: 12,
        color: '#666666',
        textAlign: 'center',
    },
    todayOverviewValueLeft: {
        marginTop: 8,
        fontWeight: 'bold',
        fontSize: 25,
        color: '#6D925E',
        textAlign: 'center',
    },
    todayOverviewValueRight: {
        marginTop: 8,
        fontWeight: 'bold',
        fontSize: 25,
        color: '#333333',
        textAlign: 'center',
    },
    todayOverviewCol: {
        flex: 1,
        alignItems: 'center',
    },
    todayBmiHeight: {
        marginLeft: 6,
        fontWeight: '500',
        fontSize: 12,
        color: '#999999',
    },
    todayBmiMetaRow: {
        marginTop: 14,
    },
    todayBmiMetaLabel: {
        fontWeight: '500',
        fontSize: 12,
        color: '#999999',
    },
    todayBmiValueRow: {
        marginTop: 8,
    },
    todayBmiValue: {
        fontWeight: 'bold',
        fontSize: 30,
        color: '#333333',
    },
    todayBmiStatusBox: {
        marginLeft: 6,
        height: 22,
        paddingHorizontal: 6,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#6D925E',
        justifyContent: 'center',
        alignItems: 'center',
    },
    todayBmiStatusText: {
        fontWeight: 'bold',
        fontSize: 11,
        color: '#6D925E',
    },
    rightBox: {
        height: 22,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        paddingHorizontal: 6,
        borderColor: '#0951AE',
    },
    rightBoxIcon: {
        width: 12,
        height: 12
    },
    rightBoxText: {
        marginLeft: 4,
        fontWeight: "bold",
        fontSize: 11,
        color: "#0951AE",
    },
    targetBox: {
        gap: 30
    },
    targetBoxText: {
        fontWeight: 500,
        fontSize: 12,
        color: "#333333",
    },
    targetBoxValue: {
        marginTop: 8,
        fontWeight: "bold",
        fontSize: 24,
        color: "#333333",
    },
    upBox: {
        marginTop: 14,
        height: 34,
        backgroundColor: "rgba(251,69,80,0.1)",
        borderRadius: 8,
    },
    upIcon: {
        width: 12,
        height: 12,
        marginRight: 6,
    },
    upText: {
        fontWeight: "bold",
        fontSize: 12,
        color: "#FB4550",
    },
    topTextBox: {
        marginTop: 12,
        height: 49,
        padding: 15,
        backgroundColor: "#FEF8E1",
        borderRadius: 8,
    },
    leftIcon: {
        width: 10,
        height: 10,
        backgroundColor: "#EE9C44",
        borderRadius: 5
    },
    typeTitle: {
        fontWeight: "bold",
        fontSize: 16,
        marginLeft: 8,
        color: "#333333",
    },
    rowValue: {
        fontWeight: "bold",
        fontSize: 16,
        color: "#333333",
    },
    rowCompareSymbol: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#333333',
        marginRight: 4,
    },
    rowTitle1: {
        marginLeft: 8,
        flex: 1,
        fontWeight: 500,
        fontSize: 14,
        color: "#333333",
    },
    rowImage: {
        width: 12,
        height: 12,
        marginRight: 6
    },
    dbBox: {
        marginTop: 8,
        padding: 15,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#D9DADD"
    },
    dbImage: {
        width: 60,
        height: 20,
        marginHorizontal: 6,
    },
    dbBoxItem: {
        flex: 1,
    },
    dbBoxItemText: {
        fontWeight: 500,
        fontSize: 12,
        color: "#333333",
    },
    dbBoxItemValue: {
        fontWeight: 500,
        fontSize: 12,
        color: "#999999",
        marginLeft: 6,
    },
    dbCol: {
        marginTop: 10,
        minHeight: 50,
        paddingHorizontal: 15,
        paddingVertical: 7,
        backgroundColor: "#F6F8FB",
        borderRadius: 8,
        width: '100%',
    },
    dbColSection: {
        width: '33.33%',
    },
    dbColTitle: {
        fontWeight: "bold",
        fontSize: 14,
        color: "#333333",
    },
    dbColTitle1: {
        fontWeight: 500,
        fontSize: 14,
        color: "#333333",
    },
    dbColValue: {
        fontWeight: "bold",
        fontSize: 16,
        color: "#999999",
    },
    dbColImg: {
        width: 14,
        height: 10,
        marginHorizontal: 8,
        flexShrink: 0,
    },
    dbColValue1: {
        fontWeight: "bold",
        fontSize: 16,
        color: "#333333",
    },
    dbRightValue: {
        fontWeight: "bold",
        fontSize: 16,
        color: "#6D925E",
    },
    dbRightValue_1: {
        fontWeight: "bold",
        fontSize: 16,
        color: "#FB4550",
    },
    dbColRightImg: {
        width: 9,
        height: 13,
        marginLeft: 7,
        flexShrink: 0,
    },

    dbRightValue1: {
        fontWeight: 500,
        fontSize: 12,
        color: "#6D925E",
    },
    dbRightValue1_1: {
        fontWeight: 500,
        fontSize: 12,
        color: "#FB4550",
    },
    btmText: {
        position: "absolute",
        bottom: 20,
        left: 0,
        right: 0,
        textAlign: "center",
        fontWeight: 500,
        fontSize: 11,
        color: "#8A8A8E",
    },
    tabBox: {
        marginTop: 14,
        gap: 6,
        flexWrap: 'wrap',
    },
    tabItem: {
        height: 30,
        flex: 1,
        minWidth: 0,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 25,
        borderWidth: 1,
        borderColor: '#E5E5E5',
    },
    tabItemActive: {
        backgroundColor: '#6D925E',
        borderColor: '#6D925E',
    },
    tabItemText: {
        fontWeight: 500,
        fontSize: 13,
        color: '#333333',
    },
    tabItemTextActive: {
        color: '#FFFFFF',
    },
    colBor: {
        width: 10,
        height: 10,
        backgroundColor: "#CFC9FF",
        borderRadius: 5
    },
    sleepPieWrap: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: '#CFC9FF',
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    sleepAnalysisBody: {
        marginTop: 16,
        width: '100%',
        alignItems: 'center',
    },
    sleepPieColumn: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sleepAnalysisLegend: {
        flex: 1,
        gap: 12,
        justifyContent: 'center',
        paddingRight: 4,
    },
    sleepAnalysisLegendRow: {
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    sleepAnalysisLegendLabel: {
        alignItems: 'center',
    },
    sleepAnalysisLegendLabelText: {
        marginLeft: 8,
        fontWeight: 500,
        fontSize: 14,
        color: '#333333',
    },
    sleepAnalysisLegendValue: {
        fontWeight: "bold",
        fontSize: 14,
        color: '#333333',
    },
    mbBox: {
        marginTop: 12,
        height: 38,
        backgroundColor: '#F6F8FB',
        borderRadius: 8,
        paddingHorizontal: 10,
    },
    mbBoxContent: {
        height: 22,
        backgroundColor: '#FFFFFF',
        borderRadius: 4,
        borderWidth: 1,
        paddingHorizontal: 6,
        borderColor: '#EE9C44',
        marginRight: 6
    },
    mbBoxText: {
        fontWeight: "bold",
        fontSize: 11,
        color: "#EE9C44",

    },
    mbBoxMessage: {
        fontWeight: 500,
        fontSize: 12,
        color: '#666666',
    },
    sleepStageDetailWrap: {
        marginTop: 12,
        marginBottom: 28,
        overflow: 'visible',
    },
    sleepStageDetailBody: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        position: 'relative',
    },
    sleepStageYLabels: {
        position: 'relative',
        zIndex: 1,
    },
    sleepStageYLabel: {
        position: 'absolute',
        left: 8,
        fontWeight: 500,
        fontSize: 11,
        color: '#B2B2B2',
        lineHeight: 16,
    },
    sleepStageEmptyPlot: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: '#F6F8FB',
    },
    sleepStageTimeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        paddingTop: 6,
    },
    sleepStageTimeBlock: {
        gap: 2,
    },
    sleepStageTimeBlockRight: {
        alignItems: 'flex-end',
    },
    sleepStageTimeDate: {
        fontWeight: 500,
        fontSize: 11,
        color: '#B2B2B2',
        lineHeight: 16,
    },
    sleepStageTimeDateRight: {
        textAlign: 'right',
    },
    sleepStageTimeText: {
        fontWeight: 500,
        fontSize: 11,
        color: '#B2B2B2',
        lineHeight: 16,
    },
    sleepStageTimeTextRight: {
        textAlign: 'right',
    },
    analysisScore: {
        fontWeight: "bold",
        fontSize: 40,
        color: "#333333",
    },
    analysisUnit: {
        fontWeight: "bold",
        fontSize: 12,
        color: "#333333",
        lineHeight: 30,
    },
    analysisDescription: {
        fontWeight: "bold",
        fontSize: 12,
        color: "#333333",
    },
    sleepScoreBarWrap: {
        marginTop: 2,
        width: '100%',
    },
    sleepScoreBarTrack: {
        position: 'relative',
        height: 12,
        backgroundColor: '#ECEDF1',
        borderRadius: 25,
        overflow: 'visible',
    },
    sleepScoreBarDivider: {
        position: 'absolute',
        top: 0,
        width: 1,
        height: 12,
        backgroundColor: '#A4AABC',
    },
    sleepScoreBarMarker: {
        position: 'absolute',
        resizeMode: 'contain',
    },
    uploadIcon: {
        width: 20,
        height: 20,
        marginRight: 16
    },
    headerTipBox: {
        paddingHorizontal: 17,
        paddingVertical: 15,
        height: 49,
        backgroundColor: "#FEF8E1",
        borderWidth: 1,
        borderColor: "#F6EDC8",
    },
    headerTipIcon: {
        width: 15,
        height: 15
    },
    headerTipText: {
        fontWeight: 500,
        fontSize: 14,
        marginLeft: 6,
        color: "#C98A41",
    }
})

export default styles
