import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
    sheetBox: {
        width: '100%',
        backgroundColor: '#FEFFFF',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        paddingTop: 24,
        paddingLeft: 18,
        paddingRight: 18,
    },
    sheetTitle: {
        width: '100%',
        fontWeight: '500',
        fontSize: 17,
        color: AppTheme.textPrimary,
        lineHeight: 24,
        textAlign: 'left',
    },
    sheetDesc: {
        marginTop: 8,
        fontWeight: '400',
        fontSize: 14,
        color: AppTheme.textSecondary,
        lineHeight: 20,
        textAlign: 'left',
    },
    sheetLogo: {
        width: 68,
        height: 68,
        marginBottom: 16,
    },
    closeBtn: {
        width: 40,
        height: 40,
        top: 8,
        right: 8,
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
    },
    rowBox: {
        width: '100%',
        padding: 16,
        marginTop: 16,
        height: 53,
        borderRadius: 11,
        borderWidth: 1,
        borderColor: AppTheme.borderColor,
        backgroundColor: '#FEFFFF',
    },
    selectBox: {
        width: '100%',
        marginTop: 16,
        borderRadius: 11,
        borderWidth: 1,
        height: 53,
        padding: 16,
        borderColor: AppTheme.primaryColor,
        backgroundColor: '#FEFFFF',
    },
    selectText: {
        fontWeight: '400',
        fontSize: 15,
        color: AppTheme.textPrimary,
        textAlign: 'left',
    },
    rowImgSize: {
        width: 21,
        height: 21,
    },
    sheetConfirmBtn: {
        width: '100%',
        height: 45,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 8,
        marginTop: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sheetConfirmBtnText: {
        width: '100%',
        fontWeight: '500',
        fontSize: 16,
        color: AppTheme.onPrimaryColor,
        textAlign: 'center',
    },
    autoSyncBtnBox: {
        width: '100%',
        marginTop: 24,
    },
    autoSyncLeftBtn: {
        width: 144,
        height: 45,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: AppTheme.primaryColor,
        backgroundColor: 'rgba(5,58,147,0.14)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    autoSyncRightBtn: {
        width: 144,
        height: 45,
        backgroundColor: AppTheme.primaryColor,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    autoSyncLeftText: {
        fontWeight: '500',
        fontSize: 16,
        color: AppTheme.primaryColor,
    },
    autoSyncRightText: {
        fontWeight: '500',
        fontSize: 16,
        color: AppTheme.onPrimaryColor,
        textAlign: 'center',
    },
    detailActionItem: {
        width: '100%',
        height: 53,
        borderRadius: 11,
        borderWidth: 1,
        borderColor: AppTheme.primaryColor,
        backgroundColor: AppTheme.onPrimaryColor,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 12,
    },
    detailActionItemDisabled: {
        borderColor: AppTheme.borderColor,
        backgroundColor: '#F5F6F8',
        opacity: 0.7,
    },
    detailActionText: {
        fontWeight: '500',
        fontSize: 16,
        color: AppTheme.primaryColor,
    },
    detailActionTextDisabled: {
        color: AppTheme.textSecondary,
    },
    detailActionCancel: {
        width: '100%',
        height: 50,
        borderRadius: 12,
        backgroundColor: AppTheme.primaryColor,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 12,
    },
    detailActionCancelText: {
        fontWeight: '500',
        fontSize: 16,
        color: AppTheme.onPrimaryColor,
    },
    autoSyncDialogOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
    },
    autoSyncDialogBox: {
        width: '100%',
        maxWidth: 352,
        backgroundColor: '#FEFFFF',
        borderRadius: 16,
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 20,
        position: 'relative',
        shadowColor: '#0C3D9A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 8,
    },
    autoSyncDialogLogo: {
        width: 68,
        height: 68,
        alignSelf: 'center',
        marginBottom: 16,
    },
    autoSyncDialogTitle: {
        fontWeight: '700',
        fontSize: 17,
        color: AppTheme.textPrimary,
        lineHeight: 26,
        textAlign: 'center',
    },
    autoSyncDialogDesc: {
        marginTop: 11,
        fontWeight: '400',
        fontSize: 15,
        color: AppTheme.textSecondary,
        lineHeight: 22,
        textAlign: 'center',
    },
    autoSyncDialogBtnBox: {
        width: '100%',
        marginTop: 24,
    },
});

export default styles;
