import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  headerGradient: { position: 'absolute', top: 0, left: 0, right: 0, height: 310 },
  body: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 30, paddingBottom: 32 },
  logo: { width: 90, height: 90, alignSelf: 'center', marginTop: 180 },
  pageTitle: { fontWeight: "bold", fontSize: 24, color: "#333333", marginTop: 20, textAlign: "center" },
  pageSubTitle: { fontWeight: 400, fontSize: 24, color: "#333333", marginTop: 6, textAlign: "center" },
  pageSubTitleBold: { color: AppTheme.primaryColor },
  title: { fontWeight: "bold", fontSize: 24, color: "#333333", textAlign: "center", marginTop: 60 },
  titleSubTitle: { fontWeight: 500, fontSize: 14, color: "#999999", textAlign: "center", marginTop: 15, marginBottom: 35 },
  inputTitle: {
    marginTop: 15,
    fontWeight: '500',
    fontSize: 16,
    color: '#333333',
  },
  inputBox: {
    marginTop: 12,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    fontSize: 16,
    color: AppTheme.textPrimary,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 2,
  },
  codeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 2,
  },
  codeInput: {
    flex: 1,
    height: 24,
    fontSize: 16,
    color: AppTheme.textPrimary,
    paddingVertical: 0,
  },
  codeBtnOff: { opacity: 0.45 },
  codeBtnText: {
    fontWeight: '500',
    fontSize: 16,
    color: '#6D925E',
  },
  buttonDisabled: { opacity: 0.6 },
  agreementRow: { marginTop: 15, gap: 8 },
  checkboxIcon: {
    width: 20,
    height: 20,
  },
  agreementText: { fontWeight: 500, fontSize: 12, color: '#999999' },
  agreementLink: { color: AppTheme.textPrimary },
  button: { marginTop: 50, height: 48, backgroundColor: AppTheme.primaryColor, borderRadius: 12, },
  buttonText: { fontWeight: 500, fontSize: 16, color: "#FFFFFF" },
  indexLoginBtn: {
    height: 48,
    backgroundColor: '#6D925E',
    borderRadius: 12,
  },
  indexLoginBtnText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  indexRegisterBtn: {
    marginTop: 25,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#6D925E',
  },
  indexRegisterBtnText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#6D925E',
  },
  registerTextBox: { marginTop: 18 },
  registerText: { textAlign: 'center', fontWeight: 500, fontSize: 13, color: AppTheme.textSecondary },
  tipBox: {
    marginTop: 'auto',
    marginBottom: 12,
    alignItems: 'center',
  },
  tipRow: {
    flexWrap: 'wrap',
  },
  tipLabel: {
    fontWeight: '500',
    fontSize: 12,
    color: '#6D925E',
    lineHeight: 20,
  },
  tipContent: {
    fontWeight: '500',
    fontSize: 12,
    color: '#999999',
    lineHeight: 20,
  },
  tipPhone: {
    fontWeight: '500',
    fontSize: 15,
    color: '#6D925E',
    lineHeight: 20,
  },
  keyboardAccessory: {
    backgroundColor: '#f7f7f7',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 12,
    height: 44,
    borderTopWidth: 1,
    borderTopColor: 'rgba(102,102,102,0.29)'
  },
})

export default styles
