import { StyleSheet } from 'react-native';
import { AppTheme } from '@/common/theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: AppTheme.backgroundColor },
  body: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 44, paddingBottom: 32 },
  title: { fontWeight: 'bold', fontSize: 24, color: '#333333', textAlign: 'center', marginTop: 60 },
  titleSubTitle: {
    fontWeight: '500',
    fontSize: 14,
    color: '#999999',
    textAlign: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  inputTitle: {
    marginTop: 15,
    fontWeight: '500',
    fontSize: 16,
    color: '#333333',
  },
  inputBox: {
    marginTop: 12,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    fontSize: 16,
    color: AppTheme.textPrimary,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 2,
  },
  yinviteCodeTip: {
    marginTop: 12,
    fontWeight: 500,
    fontSize: 13,
    color: "#999999",
  },
  codeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    height: 48,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    shadowColor: '#EAEAEA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 2,
  },
  codeInput: {
    flex: 1,
    height: 24,
    fontSize: 16,
    color: AppTheme.textPrimary,
    paddingVertical: 0,
  },
  codeBtnOff: { opacity: 0.45 },
  codeBtnText: {
    fontWeight: '500',
    fontSize: 16,
    color: '#6D925E',
  },
  buttonDisabled: { opacity: 0.6 },
  agreementRow: { marginTop: 15, gap: 8 },
  checkboxIcon: {
    width: 20,
    height: 20,
  },
  agreementText: { fontWeight: '500', fontSize: 12, color: '#999999' },
  agreementLink: { color: AppTheme.textPrimary },
  button: { marginTop: 50, height: 48, backgroundColor: AppTheme.primaryColor, borderRadius: 12 },
  buttonText: { fontWeight: '500', fontSize: 18, color: '#FFFFFF' },
  registerTextBox: { marginTop: 18 },
  registerText: { textAlign: 'center', fontWeight: '500', fontSize: 13, color: AppTheme.textSecondary },
  registerTextLink: { color: '#0951AE' },
});

export default styles;
